### ISSUE TITLE
Bazel remote caching support

### ISSUE THREAD

**Issue by gydeveloper** [buchgr/bazel-remote#105]
Hello,

We are investigating on using Bazel as our build system, and are assessing using **bazel-remote** as our remote caching. However, I am concerned that the Bazel's official documentation lists this as `experimental` and `un-supported`. 

`Bazel Remote Cache is an open source remote build cache that you can use on your infrastructure. It is experimental and unsupported.`

Can it be confirmed that this is not `experimental`? I do see that there are enough commits in the past few months that it is being supported.

**Comment by mostynb** [comment]
bazel-remote is not an official part of the bazel project, and that's probably why it's described as experimental/unsupported in the bazel docs. But bazel-remote is used in production by several companies.

This note in README.md gives some idea of bazel-remote's real-world usage:
> Project status: bazel-remote has been serving TBs of cache artifacts per day since April 2018, both on commodity hardware and AWS servers. Outgoing bandwidth can exceed 15 Gbit/s on the right AWS instance type.

**Comment by buchgr** [comment]
Agree with what @mostynb said.

**Comment by mostynb** [comment]
The status has also been clarified in the bazel docs:
https://github.com/bazelbuild/bazel/pull/10116
