### ISSUE TITLE
RFC: logging

### ISSUE THREAD

**Issue by nicolov** [buchgr/bazel-remote#11]
I was thinking of creating an Http middleware to do some logging. @buchgr did you have other ideas in mind?

**Comment by buchgr** [comment]
Yes logging is desperately needed. What exactly do you have in mind?

**Comment by nicolov** [comment]
To start, something like this: https://github.com/gorilla/handlers/blob/master/handlers.go#L331

**Comment by nicolov** [comment]
Implemented "good enough" logging support.
