### ISSUE TITLE
disk.Contains does not update the on-disk sort order

### ISSUE THREAD

**Issue by mostynb** [buchgr/bazel-remote#118]
On startup, bazel-remote scans the cache directory and sorts cache files by their atime. The Get and Put functions update the in-memory LRU index and open the file which updates the atime, but the Contains function only updates the in-memory LRU index. When bazel-remote restarts, the in-memory LRU index is lost and the new index that is recalculated will miss the effects of Contains.

Should bazel-remote update the atimes of cache files when Contains is called? This would give more correct results after restarts, but might be slower. Or should we implement a graceful shutdown process that flushes the in-memory index to disk (either by touching all the cache files in LRU order, or by explicitly dumping the in-memory LRU to disk and using that at startup time)?

**Comment by ob** [comment]
On a relatively busy server, the second option could potentially make it very expensive to shut down bazel-remote. I think distributing the `touch` calls shouldn't be that expensive... although we should probably benchmark it to make sure. I'd try the simplest approach first and see how bad it is :-)

**Comment by mostynb** [comment]
I need to think this through a bit, it might not be worth fixing at all. eg if Contains is soon followed by Get for the same key, then the atime order on disk will end up about right. And the scenario where this is a problem might be rather limited (bazel-remote instances that restart often).

**Comment by mostynb** [comment]
Doing some spring cleaning, closing this since nobody has complained about this behaviour.
