### ISSUE TITLE
RFC: compression

### ISSUE THREAD

**Issue by nicolov** [buchgr/bazel-remote#12]
I think the server should also:
- accept gzip-compressed PUT
- stream gzip-compressed PUT into a $hash.gz file without decompressing (except in a parallel stream just to check the incoming hash)
- serve a gzip-compressed stream to the bazel client from a `.gz` file without decompressing.

Object files compress very well, so this will save significant amount of IO/bandwidth. What do you think @buchgr?

**Comment by nicolov** [comment]
In my non-scientific testing, a 16GB cache directory compressed to ~ 2GB, meaning that a standard 1gbit link would go much further.

**Comment by buchgr** [comment]
Yes! I have shortly talked about it with @jgavris who wants this feature for Google Cloud Storage. I like the idea of writing and storing .gz files, as this will work with any dumb HTTP server.

I ll add this as an experimental flag to Bazel and then we can do some testing and take it from there. I’d expect the savings to be less dramatic than in your test, as Bazel would gzip each file individually while you probably gzipped a whole directory? Also, for example .jar files are already compressed and so for those it would probably have a negative effect. IIRC @jgavris mentioned some 30% savings for C++ outputs?

**Comment by jgavris** [comment]
+1 In my testing I was seeing on average about a 70% compression rate. Definitely makes that gigabit link go a lot further.

**Comment by jgavris** [comment]
For downloads, just adding content negotiation for gzip and deflate is straightforward, no? 

For uploads, would like to avoid negotiating round trips to determine if gzip / deflate is accepted, and just have the client specify this with options?

`--remote_put_compression="gzip,level=9"` ?

**Comment by nicolov** [comment]
Since it's all about opaque binary blobs, I don't think we even need to expose this to the HTTP layer. Bazel will send gzip and expect the same bytes back. This will make compression work on dumb servers too. 

To keep server-side validation of contents, we could have `bazel-remote` check for a gzip fingerprint in the first few bytes, and decompress before piping to the hash checker.

**Comment by jgavris** [comment]
Is it possible for this scheme to be totally backwards compatible? What I like about HTTP gzip is it is totally transparent and backwards compatible.

**Comment by nicolov** [comment]
Backwards compatibility is a good point. What I don't like about content-encoding is that servers and clients tend to decompress transparently, so that you end up loading your CPU twice for no good reason.

**Comment by jgavris** [comment]
Definitely, and GCS in particular does not do decompressive transcoding for this reason. I think in practice CPU's are fast and idle most of the time, for those other implementations that aren't GCS.

**Comment by nicolov** [comment]
A single core of my 3.5GHz CPU can only gzip ~ 50MB/s, so the compression overhead would be noticeable.

**Comment by buchgr** [comment]
These are good points. It's a tradeoff between your network throughput and your computing power. On my home internet connection I only get about 5MB/s in downloads and 1MB/s in uploads. I would clearly prefer to have 3x smaller outputs produced at a rate of 50MB/s. On the other hand if you are in a 10Gbit/s network, you would clearly not care about compression.

Also your CPUs probably never have to actually do much more than 50MB/s as Bazel would typically produce outputs at a much lower rate than 50MB/s. For example, Bazel has ~810MB in build outputs and it takes 120 seconds to produce them. There are some peaks where Bazel generates 100MB in 2 seconds (the final Bazel binary). Tensorflow generates less than 800MB and takes like 600 seconds to build on my machine.

What's the size of build outputs for your projects?

**Comment by jgavris** [comment]
Our project is about 600MB in build outputs. I guess it makes sense to allow the user to configure incoming and outgoing compression?

**Comment by nicolov** [comment]
Oh, try enabling CUDA in tensorflow, then try again :)

IME, build machines are CPU bound, and cache servers are network/disk
bound. This means that it makes sense to have build machines spend a little
more CPU time on gzip compression (which will be insignificant compared to
compilation, at least for c++), to save network and IO on the cache end.
This will allow a single cache server to support more developer machines.

In this scheme, I would probably add a flag to disable hash checking on the
server side, so that decompression is not needed at all. I believe that
checksums should be computed on the Bazel side when downloading build
artifacts (protecting the full round trip and distributing cpu load over
many machines). The current configuration would not scale to a 10gbit
server.

**Comment by jgavris** [comment]
I agree! For Google Cloud Storage, it will actually just store the gzipped content and not decompress it if the client will accept it coming back out, which is I guess the best of both worlds.

**Comment by jgavris** [comment]
Sorry! I keep thinking about this project mostly in the context of the bazel client. This project is the reference server! It should be possible to add compression metadata to the files written to the cache, and avoid decompressing on the way out of the client supports it.

**Comment by nicolov** [comment]
I think the easiest way would just be for bazel to always compress/decompress blobs on the way out/in. No need to change the servers at all, besides disabling the hash checks.

**Comment by buchgr** [comment]
I haven't had time to implement it yet. I agree with nicolov that there should be no need for any changes on the server side. I think we would initially want to hide it behind a flag in order to not regress performance. We would probably want to add a ".gz" ending or so to the blob names, so that both compressed and uncompressed can exist side by side.

**Comment by buchgr** [comment]
I still haven't had time to look into it :-(. If any of you wants to contribute a patch, I am happy to merge it!

Also, we are currently working on not downloading intermediate outputs at all and only downloading request (top level) outputs. Should be in Bazel soonish!

**Comment by excitoon** [comment]
@buchgr "I ll add this as an experimental flag to Bazel and then we can do some testing and take it from there."
What is this experimental flag name and which versions of Bazel have it?

**Comment by glukasiknuro** [comment]
Are there any updates for adding compression in bazel? Checking some heavy objects in our cache (500M each), using lightweight zstd compression (-3) is able to reduce some objects to 20% of their size.

Looks it can help two-fold: A) decreasing amount of network traffic and B) make cache effectively bigger.

For A) only it would be possible to enable e.g. compression in GRPC, or in HTTP using encoding at cost of compressing / decompressing network data. For B) only it would be possible to enhance remote-cache to do compression/de-compression in cache itself.

For A + B it should be possible to change bazel to be able to compress/decompress blobs and change cache to accept those, possibly for CAS only but not for action cache. Need to be careful to handle it in backward compatible way and allow remote execution to take advantage of it (add new cache capability?).

I am willing to create some design doc for A+B for some review if it will not clash with some ongong efforts, and later contribute some code.

**Comment by mostynb** [comment]
I would prefer a setup that works for both gRPC and HTTP. HTTP is simple- clients can upload compressed data and set Content-Encoding, and servers can send compressed data to clients that advertise support in the Accept-Encoding header.

But gRPC makes this complicated, because the standard bindings APIs require that clients and servers provide messages in unserialized form (ie structs in Go). So we're working on a proposal to allow transferring compressed blobs with the bytestream API: https://github.com/bazelbuild/remote-apis/issues/147 if you would like to take a look - comments welcome.

**Comment by mostynb** [comment]
Here is an early prototype of compressed-blobs bytestream support for bazel-remote:
https://github.com/mostynb/bazel-remote/tree/compressed_blobs_prototype_1

I haven't finalized the on-disk format for cas blobs, so please do not test this on important/production caches yet (existing CAS blobs will be rewritten to a new format on startup). To avoid accidents, this version of bazel-remote will refuse to start unless you specify the --destructive_compression_prototype command line flag.

**Comment by mostynb** [comment]
The compressed-blobs support (with zstandard compression) has landed.
