### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by joprice** [buchgr/bazel-remote#138]
I can't seem to build this project. I get the following error when running `bazel build ...`:

```
compilepkg: missing strict dependencies: ... import of "golang.org/x/sys/unix"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
```

**Comment by mostynb** [comment]
Which commit are you trying to build, and with which version of bazel?

**Comment by mostynb** [comment]
I can reproduce this on mac, I think it's a variation of https://github.com/bazelbuild/rules_docker/issues/690

If you just want to build a bazel-remote binary on/for mac, this should work:
`bazel build //:bazel-remote`

**Comment by joprice** [comment]
I was trying to build both from a mac for mac to test local changes, and for linux with the intent to run it in docker. These two commands work perfectly for me. Thank you
