### ISSUE TITLE
grpc uploads broken

### ISSUE THREAD

**Issue by gjasny** [buchgr/bazel-remote#146]
Hello,

while working on an unrelated feature I noticed that when using the grpc transport instead of http I did not get any cache hits.

bazel-remote: master / 871dbe45a876d4df42e384d686b3848771740764
bazel 2.0.0
macOS: 10.15.2

To reproduce start with a clean cache:

```
mkdir -p ~/tmp/cache
rm -rf ~/tmp/cache/*
bazel run //:bazel-remote -- --dir ~/tmp/cache --max_size 2
```

Then build abseil/algorithm two times with cleaning in between:
```
bazel build --remote_upload_local_results=true --remote_cache=grpc://localhost:9092/ //absl/algorithm/...

bazel clean

bazel build --remote_upload_local_results=true --remote_cache=grpc://localhost:9092/ //absl/algorithm/...
INFO: Invocation ID: edd7d4b9-9ad6-4dd2-a7dd-e005bd2b36ef
INFO: Analyzed 5 targets (29 packages loaded, 517 targets configured).
INFO: Found 5 targets...
INFO: Elapsed time: 13.772s, Critical Path: 8.59s
INFO: 56 processes: 56 darwin-sandbox.
INFO: Build completed successfully, 75 total actions
```

Expectation is to get 100% cache hits. Result is none at all.

In contrast the http backend behaves as expected:

```
mkdir -p ~/tmp/cache
rm -rf ~/tmp/cache/*
bazel run //:bazel-remote -- --dir ~/tmp/cache --max_size 2
```

```
bazel build --remote_upload_local_results=true --remote_cache=grpc://localhost:9092/ //absl/algorithm/...

bazel clean

bazel build --remote_upload_local_results=true --remote_cache=http://localhost:8080/ //absl/algorithm/...
INFO: Invocation ID: d03788fb-dcb6-45f0-b98b-b0622a98a8fe
INFO: Analyzed 5 targets (29 packages loaded, 517 targets configured).
INFO: Found 5 targets...
INFO: Elapsed time: 3.727s, Critical Path: 0.19s
INFO: 56 processes: 56 remote cache hit.
INFO: Build completed successfully, 75 total actions
```

100% hit ratio as expected.

Funny thing is that if you use grpc on a http-prewarmed cached you also get 100% hits:
```
bazel clean

bazel build --remote_upload_local_results=true --remote_cache=grpc://localhost:9092/ //absl/algorithm/...
INFO: Invocation ID: 2b60d65c-5936-411b-ac65-384d39284a86
INFO: Analyzed 5 targets (29 packages loaded, 517 targets configured).
INFO: Found 5 targets...
INFO: Elapsed time: 3.369s, Critical Path: 0.25s
INFO: 56 processes: 56 remote cache hit.
INFO: Build completed successfully, 75 total actions
```

So I suspect that something in the grpc upload is broken on either the cache or bazel side.

Thanks,
Gregor

PS: I have `common --logging 6` in my `~/.bazelrc` to see the hit ratio in the console output

CC: @mostynb

**Comment by mostynb** [comment]
Thanks for catching this! The culprit was https://github.com/buchgr/bazel-remote/pull/130

I think https://github.com/buchgr/bazel-remote/pull/147 will fix this, and I will follow up with some better test cases to cover this later.
