### ISSUE TITLE
refactor the cache.Cache interface

### ISSUE THREAD

**Issue by mostynb** [buchgr/bazel-remote#161]
I think we should refactor the cache.Cache interface. At the moment we have a single cache.Cache interface that is used both by the disk backend and the proxy backends (s3, http/gcs). The proxy backends contain the same mostly copy+pasted logic for using the local/disk backend, and just forward some calls (like Stats) directly to the local/disk backend.

Instead, we could move the duplicated logic into the disk backend, and have the disk backend make calls to an optional proxy backend. The proxy backends would then implement a smaller interface, and their code would be simpler. This in turn would make it simpler to implement action cache data integrity checks in one place (the disk backend).

**Comment by mostynb** [comment]
@buchgr: I think it makes sense to do this refactoring before attempting the action cache/sync changes.

**Comment by buchgr** [comment]
Sounds about right.
