### ISSUE TITLE
Automatically deploy to DockerHub

### ISSUE THREAD

**Issue by buchgr** [buchgr/bazel-remote#163]
We should setup a job to CI that automatically deploys changes in master to Dockerhub.

**Comment by mostynb** [comment]
Alternatively maybe we can turn the dockerhub account into an group/organisation, so I can upload manually. Not sure if that's possible.

**Comment by mostynb** [comment]
@buchgr: could you please deploy the 1.3.1 release to dockerhub?

**Comment by buchgr** [comment]
Done. Yep we should turn it into an organizational account. Can you send me an e-mail please so can talk details?

**Comment by mostynb** [comment]
Thanks- emailed.

**Comment by MaciejKucia** [comment]
If you could consider uploading ARM images it would be wonderful. Public cloud ARM machines are cheaper than x86 and quite good!

**Comment by mostynb** [comment]
> If you could consider uploading ARM images it would be wonderful. Public cloud ARM machines are cheaper than x86 and quite good!

Opened a new issue for this: #450.
