### ISSUE TITLE
Can I rsync one remote cache to another, or sync them in some other way?

### ISSUE THREAD

**Issue by honicky** [buchgr/bazel-remote#166]
Hi there,

I'm not sure if this is the right way to ask this question, but I don't see a better forum, and I didn't get any response on stack-overflow, so I'm asking in this ticket.  I'm happy to ask somewhere more appropriate if you point me there.

I have a build pipeline that builds and tests changes before they are merged to the main line. Once that happens, it would be great if the Bazel actions from that build are available to developers. Unfortunately, the build pipeline runs in the cloud and uses an in-cloud cache, but the developers use an on-premises cache.

I use your docker image and run using docker-compose.

Does anyone know if I can just rsync the artifacts from the data directory of the cloud cache to the developers' cache in order to give them access to the pre-built artifacts? Normally, I would just try it out, but I'm concerned about subtle issues that might poison the cache or negatively effect the hit rate, so I'm hoping to hear from someone who understands the code before I go digging.

Thank in advance!

**Comment by mostynb** [comment]
You can rsync the cache files around, and start another bazel-remote instance pointing at the new location. But this won't work with a running bazel-remote instance (the files will be ignored until you restart bazel-remote).

Another option might be to use the http proxy backend on your on-premises cache, to proxy requests to the in-cloud cache.

**Comment by honicky** [comment]
Ok, thanks.  The whole point of having the on-prem cache is to avoid going over the WAN to satisfy requests, so I'll see what I can do with the first option.  Perhaps ha-proxy can work.

I consider this issue closed, but I'll leave it open in case you want to do something else with it.

Thanks a lot for your fast response!

**Comment by mostynb** [comment]
The proxy backend setup checks the local disk cache first, and only talks to the proxy if there's a local cache miss. Whether or not that makes sense for you will depend on things like the speed of your WAN link and the size of the cache items.

If you want to populate one bazel-remote instance from another after a build you could put together a small python/bash/whatever script that walks the cache directory, and then uploads them to the second bazel-remote instance using the HTTP. You might want to sort the items by mtime before uploading in oldest-first order, and maybe skip items with mtime before a certain cutoff.

I will close this issue now, but feel free to open more issues here (or reuse this issue for followup questions). The only other place I can suggest trying for help with bazel-remote is the bazel slack: https://slack.bazel.build/
