### ISSUE TITLE
Support IAM roles

### ISSUE THREAD

**Issue by radix-aw** [buchgr/bazel-remote#172]
It would be very helpful if bazel-remote could read S3 access tokens from instance metadata, as described [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials).

**Comment by mostynb** [comment]
I'm not sure that I understand the use case- could you explain what you would like this to do and how it might work?

**Comment by radix-aw** [comment]
I am running bazel-remote on an EC2 instance. I would like to use S3 as a backend, but rather than provide a static access key, I can use Amazon's IAM feature. I can assign a role to the instance (say, "caching-server") and attach an IAM policy which allows read/write access to the S3 bucket.

As described in the documentation, the access token can be retrieved by accessing the following URL:

`curl http://169.254.169.254/latest/meta-data/iam/security-credentials/role_name`

Much of this logic is already provided in [minio-go](https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go), a library upon which you already depend.
