### ISSUE TITLE
Odd failures happen when ulimit -n isn't set high enough

### ISSUE THREAD

**Issue by brentleyjones** [buchgr/bazel-remote#174]
3f629263b38fb36432431406a2765029d6c1aa34 introduced a regression with the disk cache. Before this commit we could perform the following:

```
bazel clean
bazel build --remote_cache=grpc://localhost:9092 --experimental_remote_download_outputs=minimal --experimental_inmemory_jdeps_files --experimental_inmemory_dotd_files //...
```

And we would have a successful build.

With the changes we now get lots of 404s, some of which will result in Build without the Bytes failing:

```
ERROR: [redacted]/BUILD.bazel:3:1: StoryboardLink [redacted] failed due to unexpected I/O exception: Failed to fetch file with hash '9aab509077a327cf9ddddea85c087b822046348120e179526c661f283ed6da45' because it does not exist remotely. --experimental_remote_outputs=minimal does not work if your remote cache evicts files during builds.
java.io.IOException: Failed to fetch file with hash '9aab509077a327cf9ddddea85c087b822046348120e179526c661f283ed6da45' because it does not exist remotely. --experimental_remote_outputs=minimal does not work if your remote cache evicts files during builds.
```

**Comment by mostynb** [comment]
Can you describe your setup bit:
* How large is your disk cache?
* How large is your proxy backend?
* How much disk space is used for the cache items for a single build?

**Comment by brentleyjones** [comment]
- I have the limit set to 20gb. This error appears after the first successful build, and at that point the cache is at 1GB
- We don't have a proxy backend in this repo.
- 1.0GB per `du -hs`.
- They exist on disk under the `cas` directory.
- This is a single local instance.

**Comment by mostynb** [comment]
Strange. Could you restart bazel-remote and redirect the output to a file, then do a rebuild (which fails), pick one of the blobs that causes bazel to fail and grep the log file for that hash and share the results here?

**Comment by mostynb** [comment]
Also, since you're using experimental bazel features- which version of bazel are you using?

**Comment by brentleyjones** [comment]
2.0.0. I'll get the relevant part of the logs.

**Comment by brentleyjones** [comment]
Retesting and now everything is working fine.

What I did change in-between the tests though is I increased the maximum number of open files for my shell, since I was seeing errors like this:

**Comment by mostynb** [comment]
Right- forgetting to increase the number of open file handles is an easy mistake to make (one I often make myself). Maybe we should mention this in the readme file.

Can you perform a test with the ulimit -n set to the default value, and see if that reliably triggers the error? It might also be worth comparing the behavior when using http vs grpc (grpc is more likely to require a higher ulimit -n setting in my experience).

**Comment by brentleyjones** [comment]
Sure. I will note I got the error on both http and grpc, since I thought the same thing.

**Comment by brentleyjones** [comment]
So it's `ulimit -n` related:

Build:
```
WARNING: Writing to Remote Cache:
INTERNAL: open /Users/z002wrr/.cache/bazel-remote-target/flagship/ios/ac/23/2367443d0f6000416ebbe6841a998b67355f2140ac4134b32194d29b56b461ac.tmp: too many open files
WARNING: Writing to Remote Cache:
INTERNAL: open /Users/z002wrr/.cache/bazel-remote-target/flagship/ios/ac/d5/d5673879460573195533309b2710bfe0ed2c30b82121d582b6636cc40f06b756.tmp: too many open files
ERROR: /private/var/tmp/_bazel_z002wrr/e0bd9ecd2285aaf648301a3882abd468/external/com_google_protobuf/BUILD:106:1: Linking of rule '@com_google_protobuf//:protobuf_lite' f
ailed due to unexpected I/O exception: Failed to fetch file with hash '16b980cdbee2a7e183652e0b69fc4d52a12e22019cde0e7d41690d7fef82f1e0' because it does not exist remotel
y. --experimental_remote_outputs=minimal does not work if your remote cache evicts files during builds.
java.io.IOException: Failed to fetch file with hash '16b980cdbee2a7e183652e0b69fc4d52a12e22019cde0e7d41690d7fef82f1e0' because it does not exist remotely. --experimental_
remote_outputs=minimal does not work if your remote cache evicts files during builds.
```

cache:
```
2020/02/03 20:44:18 GRPC AC PUT 0c909acd8682bfe2de7c6c51ea4b361763f3ea394f0079e363bfc0aed0a40ff1 open /Users/z002wrr/.cache/bazel-remote-target/flagship/ios/ac/0c/0c909acd8682bfe2de7c6c51ea4b361763f3ea394f0079e363bfc0aed0a40ff1.tmp: too many open files
2020/02/03 20:44:19 GRPC AC PUT d5673879460573195533309b2710bfe0ed2c30b82121d582b6636cc40f06b756 open /Users/z002wrr/.cache/bazel-remote-target/flagship/ios/ac/d5/d5673879460573195533309b2710bfe0ed2c30b82121d582b6636cc40f06b756.tmp: too many open files
2020/02/03 20:44:19 GRPC AC GET 12d1d766502f0c6521caa957d46adae8f49940725744cb1d6a3c1cfc6dafbc8e NOT FOUND
2020/02/03 20:44:19 GRPC BYTESTREAM READ BLOB NOT FOUND: 5af46e51fae5a2fe090602ecf39ee6457709464cf59fcabcadc5e3bb30f3c097
2020/02/03 20:44:19 GRPC BYTESTREAM READ BLOB NOT FOUND: fcf1949bc2fd0d4bf38137563363f65da2a01d3f88dfe19d045135d67572887a
2020/02/03 20:44:19 GRPC BYTESTREAM READ BLOB NOT FOUND: e10a6fb5a0bf52386303dada939b9e5e665837233fdeaff1ec9715fc06fa320d
2020/02/03 20:44:19 GRPC BYTESTREAM READ BLOB NOT FOUND: 16b980cdbee2a7e183652e0b69fc4d52a12e22019cde0e7d41690d7fef82f1e0
```

----

Switching between `unlimit -n` reproduces it (so it's related to opening the file I bet).

**Comment by mostynb** [comment]
I wonder if there's an easy way to monitor the number of open files in your process tree on mac, to check if we're leaking file descriptors (it might just be a temporary leak until GC kicks in).

**Comment by brentleyjones** [comment]
Do we want to automatically increase the soft ulimit similar to https://github.com/bazelbuild/bazel-watcher/blob/cc87648527cfbc7dd8fdb7484176ac62345dfed5/ibazel/main_unix.go?

**Comment by mostynb** [comment]
Automatically raising `ulimit -n` sounds good to me.

Here's another solution, without the hardcoded macos upper limit: https://github.com/cockroachdb/cockroach/commit/5141c2cbe34ea8c6f07547f0ffe7a35adfa5aeb4
