### ISSUE TITLE
uncommitted cache files leak when evicted from the LRU index

### ISSUE THREAD

**Issue by mostynb** [buchgr/bazel-remote#176]
The disk cache's `onEvict` function is called on the least-recently used cache item after it has been removed from the index (map + list), to remove the file from disk. But if that cache item was uncommitted (ie, there was an active upload to a temp file) then `onEvict` does nothing:
https://github.com/buchgr/bazel-remote/blob/f99b78caaa2f0483cb838eda1c68cb9fc3d90b56/cache/disk/disk.go#L88

When such an upload finishes, the temp file is renamed, but it is no longer in the index and not counted as using up disk space.

I think this is an old bug that predates the `cache.Cache` refactoring- earlier, random temp files whose names were known only to the in-progress `Put` call goroutine were used for uploading blobs, which is probably why `onEvict` did not attempt the remove them. But since we now use a predictable temp file name (the blob name with `.tmp` appended), `onEvict` could remove the file.

**Comment by Zetten** [comment]
I'm testing a branch with both #177 and #178 merged, and unfortunately still getting some errors. Although it does seem to be a bit more resilient.

Errors in the build log:
```
2020-02-05 09:38:25.959   WARNING: Reading from Remote Cache:
2020-02-05 09:38:25.959   io.grpc.StatusRuntimeException: UNKNOWN: GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
```

It looks like this blob was previously cached in S3, but evicted from the local disk. This particular entry is ~130 MB, so it may just remain an issue when there's a cluster of large files meeting at once, and overflowing the ~1GB breathing room in the 5GB volume?

(possibly there are some concurrent requests, or some retry logic here?)
```
2020/02/05 09:38:20 S3 CONTAINS cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:20 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:20 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:20 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:20 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:20 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:21 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:21 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:21 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:22 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:23 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:25 S3 DOWNLOAD cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:25 GRPC BYTESTREAM READ FAILED: write /data/cas/0e/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4.tmp: no space left on device
2020/02/05 09:38:26 S3 CONTAINS cgici-bazel-cache cache/cas/0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
2020/02/05 09:38:26 GRPC CAS HEAD 0e859995c0528c87c8ceff214a28b85c8307d6fc18ade38f2bc04651ba5a1dd4 OK
```

Similarly we have a PUT error (not sure the size of this one):
```
2020/02/05 09:38:22 S3 CONTAINS cgici-bazel-cache cache/cas/b65704e1c415a8e1b654f53d3fa62340157a02aa1071b56c6e2ff5de26698ce9 NOT FOUND
2020/02/05 09:38:22 GRPC CAS HEAD b65704e1c415a8e1b654f53d3fa62340157a02aa1071b56c6e2ff5de26698ce9 NOT FOUND
2020/02/05 09:38:24 GRPC BYTESTREAM WRITE CACHE ERROR: write /data/cas/b6/b65704e1c415a8e1b654f53d3fa62340157a02aa1071b56c6e2ff5de26698ce9.tmp: no space left on device
2020/02/05 09:38:24 ERROR: failed to remove evicted item: /data/cas/b6/b65704e1c415a8e1b654f53d3fa62340157a02aa1071b56c6e2ff5de26698ce9 / /data/cas/b6/b65704e1c415a8e1b654f53d3fa62340157a02aa1071b56c6e2ff5de26698ce9.tmp
```

I was hoping the S3 cache backend would remove the need for a large disk cache, but I can increase the volume size if that's a necessary part of the design.

**Comment by mostynb** [comment]
The errors posted above are exactly what is expected when the filesystem is full- the actual problem must occur before these logs. What do the /status and /debug URLs show when in this state?

**Comment by mostynb** [comment]
> I was hoping the S3 cache backend would remove the need for a large disk cache, but I can increase the volume size if that's a necessary part of the design.

In my experience undersized caches can be worse than no cache. What counts as "undersize" depends on the use case, of course (factor in things like the churn rate, blob size, size of a complete build set, how predictable the cache access patterns are etc).

If you're running your cache on AWS then maybe s3 access is fast (I have no idea about this), maybe it would be better to not have a disk cache? bazel-remote doesn't currently support that mode, but it could be added if it was useful.

**Comment by Zetten** [comment]
I'd certainly be willing to test a direct S3 passthrough mode to compare performance vs. a disk volume.

On a related note I was thinking about testing https://github.com/Asana/bazels3cache as a sidecar container to our build containers, so traffic is directly between bazel - localhost - S3, rather than via a cache service somewhere else in the Kubernetes cluster (and incurring additional network burden).

But bazels3cache doesn't support the gRPC interface, plus I haven't had the time. But if bazel-remote can work in this mode, that'd be perfect.

Anyway, stats with the debug+177+178 branches:

The status page:
```
{
 "CurrSize": 4022252826,
 "MaxSize": 4294967296,
 "NumFiles": 5447,
 "ServerTime": 1580906845,
 "GitCommit": "e12e8c4dca2d9329a3dc43537181693bd6b93574"
}
```

The debug page:
```
expected CurrentSize: 4022252826
expected NumItems: 5447
Actual CurrentSize: 5158538314 Expected: 4022252826
No bad items found.
```

And the real disk stats:
```
# find . -type f | wc -l
5447
# du -s .
5058148	.
```

**Comment by mostynb** [comment]
The numbers above show that no cache files have leaked, and that the currentSize tally has gone out of sync somewhere. I haven't been able to reproduce this locally yet, but I'll do another pass over the code.

**Comment by brentleyjones** [comment]
Another vote for a pass-through mode, specifically for setting max cache size different for disk than backend. Since https://github.com/Asana/bazels3cache is in the "dumb cache" category it doesn't support Remote Builds without the Bytes.

**Comment by mostynb** [comment]
What are the requirements of a cache for "builds without the bytes"?

Note that bazel-remote's proxy mode only keeps track of the disk cache size, it makes no attempt to impose a storage limit on the proxy backends.

**Comment by buchgr** [comment]
> What are the requirements of a cache for "builds without the bytes"?

The only requirement is to not serve action results with references to dead CAS entries.

**Comment by mostynb** [comment]
@Zetten: I think I found the undercount, potential fix: https://github.com/buchgr/bazel-remote/pull/177/commits/1d308555b5c8a94066c2a19b4e9d6d324f10de47

**Comment by Zetten** [comment]
All is running nicely with the new commit! :tada:

Having watched it for a little while, I think the issue was exacerbated by a few exceptionally large objects - combined with, like you mentioned, an undersized disk cache for this load. I'll be increasing the volume size to reduce the churn, but bazel-remote seems pretty resilient to it now; no overflowing max_size that I can see.

Thanks for all your work tracking this down and fixing the various issues.

**Comment by mostynb** [comment]
Thanks for helping test this.

I will try to experiment with a proxy-only mode once I finish a few other in-progress features.
