### ISSUE TITLE
Metrics for http- vs grpc- cache

### ISSUE THREAD

**Issue by pcj** [buchgr/bazel-remote#183]
Now that this repo also has a grpc-cache, has anyone recorded metrics on how they compare performance-wise?

**Comment by mostynb** [comment]
I don't have detailed numbers at hand, but apparently bazel uploads outputs concurrently with gRPC and sequentially with HTTP, making gRPC noticeably faster in some cases:
https://github.com/buchgr/bazel-remote/pull/162#issuecomment-578044035

**Comment by pcj** [comment]
I'll go ahead and close this, thanks for info.
