### ISSUE TITLE
Builds fail on cache hit

### ISSUE THREAD

**Issue by philwo** [buchgr/bazel-remote#198]
After upgrading bazel-remote today to the latest master branch on Bazel's CI, I observed that a couple of our builds started failing like this:

https://buildkite.com/bazel/rules-jvm-external/builds/1259#1c9d4ee6-1b1f-47a4-b27c-8f2d3c90e2fb

whereas a successful build using a non-broken bazel-remote server would look like this:

https://buildkite.com/bazel/rules-jvm-external/builds/1261#a8eaa795-ce36-4897-ba49-faeb3b9fd2b1

The breakage only happens when Bazel gets cache hits. I used `git bisect` to find this culprit:
https://github.com/buchgr/bazel-remote/commit/b2e2f705f43d20e12dd8139f1719e7bd9c40a9b2

I looked at it for a while, but don't see any obvious problem 😬
Still, if I revert just this commit, everything works fine again...

**Comment by philwo** [comment]
I bisected this on our CI line by line and ... it's this one:

https://github.com/buchgr/bazel-remote/commit/b2e2f705f43d20e12dd8139f1719e7bd9c40a9b2#diff-c345d80c83f6632025fff533f194977fR645

```diff
-		data, err := ioutil.ReadAll(r)
+		data, err = ioutil.ReadAll(r)
```

**Comment by mostynb** [comment]
Oops- thanks! Would you like to create a PR or shall I?

**Comment by philwo** [comment]
Sorry - forgot to tag this issue in the PRs! It’s fixed in #199 and #200. :) Closing this issue then!

**Comment by mostynb** [comment]
Thanks again, and sorry about the regressions.

**Comment by philwo** [comment]
No worries and thank you for maintaining this project!
