### ISSUE TITLE
Add a "status" request that shows some information about the cache

### ISSUE THREAD

**Issue by iphydf** [buchgr/bazel-remote#2]
Such as current size, number of objects, etc.

**Comment by buchgr** [comment]
Hi @iphydf! Good idea. Where you thinking of a html page?

**Comment by iphydf** [comment]
Yes I was but maybe a json response would be even better so I can write my own html to display it on my website.

**Comment by buchgr** [comment]
Sounds good! If anyone wants to tackle this issue feel free! But please leave a comment here so that we don’t work on it concurrently :-)

**Comment by nicolov** [comment]
This is already implemented under `/status`.
