### ISSUE TITLE
Allow setting object's access control list for S3

### ISSUE THREAD

**Issue by thii** [buchgr/bazel-remote#204]
It would be nice to be able to set ACL to public read so that the S3/Minio endpoint can serve as a static cache server. Currently all files uploaded to the S3 backend are being set as private.

**Comment by mostynb** [comment]
I think it might be better to set this policy on the s3/minio server side, if possible.

**Comment by thii** [comment]
AFAIK it's not possible to set this policy per bucket basis, but per object basis, so I think it might be better if we can set this when each object gets uploaded, rather than revisit them after they have been uploaded and change their access policy.

**Comment by mostynb** [comment]
I think this should be possible with minio, but I have not tried it myself:
https://gist.github.com/krishnasrinivas/2f5a9affe6be6aff42fe723f02c86d6a

**Comment by thii** [comment]
TIL. Thanks a lot!

**Comment by thii** [comment]
Although the bucket's ACL was set to public, `bazel-remote` still sets each file's ACL to private when uploading them.

**Comment by mostynb** [comment]
I don't think minio supports ACLs, `ObjectACL` is in the list of unsupported APIs:
https://github.com/minio/minio/blob/master/docs/minio-limits.md

They suggest bucket policies instead:
https://docs.min.io/docs/minio-client-complete-guide#policy

Is this what you tried, or something else?

**Comment by thii** [comment]
> I don't think minio supports ACLs, ObjectACL is in the list of unsupported APIs

Yeah, it was supported in an older version. Not sure why it was removed. However, I was able to work around that by adding a `x-amz-acl` metadata here.

https://github.com/buchgr/bazel-remote/blob/0256771d28c5d706fedb4d386e880ccbb1fa9b24/cache/s3/s3.go#L141-L143

What do you think about reading the bucket policy ACL and setting it as the default ACL for each `PutObject` request?

**Comment by mostynb** [comment]
If we add this feature, it would need to be configurable (and probably off by default). I will experiment with minio to see if I can get the bucket policy to work first, because that would keep things slightly simpler.

**Comment by mostynb** [comment]
This seems to WFM:

    # Create a new minio server:
    ~/go/bin/minio server test &

    # Add a new host alias(?) with the default username/password:
    ~/go/bin/mc config host add myminio http://127.0.0.1:9000 minioadmin minioadmin
    # Create a bucket:
    ~/go/bin/mc mb myminio/bazel-remote

    # Make a build, using a bazel-remote instance with the s3 proxy backend pointing to
    # 127.0.0.1:9000 with username/password minioadmin/minioadmin and prefix set to "files":
    cd ~/go/src/github.com/buchgr/bazel-remote
    bazel clean ; bazel build //:bazel-remote --remote_cache=grpc://127.0.0.1:9092

    # Confirm that anonymous access is rejected (for a blob that's known to exist):
    wget -O - http://127.0.0.1:9000/bazel-remote/files/ac/4f776d69d12ab05a1074474c1a542f88049dbca637c377228d1824ad213ecfaa

    # Set the default/anonymous policy to readable/download:
    ~/go/bin/mc policy set download myminio/bazel-remote/files
    # Confirm that anonymous reads work:
    wget -O - http://127.0.0.1:9000/bazel-remote/files/ac/4f776d69d12ab05a1074474c1a542f88049dbca637c377228d1824ad213ecfaa

**Comment by mostynb** [comment]
I notice that the ceph info says `Policy:    none` - can you try adding a `s3:GetObject` policy for Principal `"*"`?

Ref: https://docs.ceph.com/docs/mimic/radosgw/bucketpolicy/

Here's someone who seems to have succeeded, they were able to set the policy using a small python script:
https://stackoverflow.com/questions/50400687/ceph-radosgw-bucket-policy-make-all-objects-public-read-by-default

**Comment by thii** [comment]
Works like a charm. Thanks again.
