### ISSUE TITLE
Increasing the `--max_size` option to 1T or even more

### ISSUE THREAD

**Issue by mashayev** [buchgr/bazel-remote#227]
Hey All,

We are using bazel and our repository is big one, when building the whole repository (We have these cases) we are creating more than 50G of data and more than 50 millions of files.
Today the remote cache is set with 200G of max size.

I wonder how will it effect the performance of the remote cache server if I will set the option to 1T / 2T or even more?

1. Will it require just a bigger instance?
2. Can the remote cache server handle this amount of cache size?
3. Is there any relation between repo size and the remote cache `--max_size` option?

**Comment by mostynb** [comment]
Caches of a few terabytes work fine for me (use SSD-speed storage if at all possible).

As long as the index fits in memory there's no significant difference compared to a smaller cache. However I'm not sure if anyone has tried bazel-remote with "millions of files", that might cause trouble depending on the filesystem that you're using, and might require some experimentation.

**Comment by mostynb** [comment]
Marking this issue as closed, please reopen if this hasn't answered your questions.
