### ISSUE TITLE
Issue with bazel remote cache docker image

### ISSUE THREAD

**Issue by basavaraj29** [buchgr/bazel-remote#241]
I'm trying to experiment with bazel remote cache. Everything seems to function pretty well, but sometimes this error is consistent, though there there is no connectivity issue. Is there any other reason for this or am I missing something here? Thanks. 
```
2020/04/01 07:33:47 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:34:47 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:35:48 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:36:50 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:37:51 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:38:54 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:39:54 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:40:55 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:41:55 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:42:56 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:43:57 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
2020/04/01 07:44:59 GRPC BYTESTREAM WRITE FAILED: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by mostynb** [comment]
Is the bazel-remote server under heavy load (lots of simultaneous requests) when you see this error? I think DeadlineExceeded means that the request was not finished before the timeout value specified by the client.

You might be able to play with bazel's `--http_timeout_scaling` flag on the client side to increase the timeout:
https://docs.bazel.build/versions/master/command-line-reference.html#flag--http_timeout_scaling

**Comment by basavaraj29** [comment]
As an initial step, I was trying out with a single machine writing to the cache. 

From the documentation, 
```
http_timeout_scaling: Scale all timeouts related to http downloads by the given factor
``` 
isn't this the timeout scaling factor for http get requests? But in my case there were intermittent failures during gRPC write calls from the client side.

**Comment by mostynb** [comment]
I'm not sure if `--http_timeout_scaling` also covers uploads, but I couldn't see any other flags that looked relevant in the bazel docs. After grepping the bazel source just now I think `--remote_timeout` might do the trick:
https://docs.bazel.build/versions/master/command-line-reference.html#flag--remote_timeout

Do you know how large these build artifacts happen to be?

**Comment by basavaraj29** [comment]
Not sure about the size as there are multiple targets being processed. Will try playing around with `--remote_timeout` and see if it helps. Thank you.

**Comment by mostynb** [comment]
No problem. Please let me know if this helps :)
