### ISSUE TITLE
Implement remote downloader APIs

### ISSUE THREAD

**Issue by robbertvanginkel** [buchgr/bazel-remote#255]
There is a bazel feature that can be enabled with the [`--experimental_remote_downloader`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_remote_downloader) flag that lets bazel use its remote exec CAS as a remote repository cache. The [remote downloads proposal](https://github.com/bazelbuild/proposals/blob/master/designs/2020-01-14-remote-downloads.md) defines a few gprc/proto apis to associate cas blobs with urls (or other qualifiers) so bazel can fetch these from the cas, rather than from the respective origin directly.

Would it makes sense for this project to implement (some of) the remote download apis? Implementing the read-through parts of `Fetcher` might be a bit out of scope, but it'd be great if this project could support the `Pusher` APIs and `Fetcher` for pushed blobs.

**Comment by mostynb** [comment]
I have an experimental (partial) implementation over here:
https://github.com/mostynb/bazel-remote/tree/fetch_api

I only heard about the bazel client implementation last week, but it seemed to work in a quick test. My branch needs a bit of cleanup, but I might land it disabled behind a command line arg in the near future.

If you're interesting in collaborating on development, there's a (quiet) #bazel-remote-asset-api channel on the bazel slack (join at https://slack.bazel.build/).

**Comment by robbertvanginkel** [comment]
Oh awesome! I'll take a look at the branch and reach out on slack if I have any questions.

**Comment by brentleyjones** [comment]
>If you're interesting in collaborating on development, there's a (quiet) #bazel-remote-asset-api channel on the bazel slack (join at https://slack.bazel.build/).

I don't see that channel?

**Comment by mostynb** [comment]
Oops, try #remote-asset-api instead.

**Comment by mostynb** [comment]
I landed the experimental remote asset API branch on master just now, behind a runtime flag: #276.

Hopefully this makes it easier for people to try out. Improvements welcome.
