### ISSUE TITLE
Duplicate data

### ISSUE THREAD

**Issue by nouiz** [buchgr/bazel-remote#263]
Hi,

It happens that multiple keys end up to the exact same data. In such case, will there be a deduplication on the server to save disk spaces? Or is it the responsibility of each project to not create duplicate keys?

**Comment by mostynb** [comment]
Hi, bazel-remote only stores one value for each CAS key, and one value for each Action Cache (AC) key. There is no need for clients to deduplicate blobs.

**Comment by nouiz** [comment]
I understand that part. A full example of what I'm asking.

A project needs one env variable for some files, but this env variable isn't used in all compiled files. In 2 different compilations runs, we use different values for that env variable. This will generate a different key for all files compiled.
For the files that don't use that env variable, we will end up with multiple keys that point to the same data. Does the cache de-duplicate that specific data to save disk space?

**Comment by brentleyjones** [comment]
What is stored in the CAS is the actual output, and it's keyed off of a digest of the contents of the blob. If two unique actions (per your description) generate the same output, Bazel will only upload it once since bazel-remote will state that it already exists in the CAS under its digest.

**Comment by nouiz** [comment]
Thanks.

**Comment by mostynb** [comment]
Just to expand on this a little- even if the client were to upload the same CAS blob multiple times, bazel-remote will only keep one copy.

**Comment by nouiz** [comment]
Great. This is the behavior that I was looking for. And it is safe, as the dedup is done at 2 levels.
