### ISSUE TITLE
Docker Deploy Request

### ISSUE THREAD

**Issue by UebelAndre** [buchgr/bazel-remote#268]
I noticed there are a lot of commits that are not reflected in the latest [dockerhub tag](https://hub.docker.com/r/buchgr/bazel-remote-cache/). Would it be possible to deploy a new release or could you explain what the criteria is for release?

Thanks!

**Comment by mostynb** [comment]
I plan to make a new release in the next few days. We don't have a formal release criteria at the moment, and I don't have access to upload it myself, so it might take a little longer to reach dockerhub.

**Comment by UebelAndre** [comment]
Awesome! Really looking forward to that! thank you!  😃
