### ISSUE TITLE
RFC: Differential downloads

### ISSUE THREAD

**Issue by michaeleisel** [buchgr/bazel-remote#269]
Binary diffing has been done successfully to deliver incremental changes for large binaries with a small download size. For example, Chrome uses it in delivering updates. There are multiple tools out there that can do this, for example bsdiff and [Courgette](https://www.chromium.org/developers/design-documents/software-updates-courgette). Would that be viable to add to reduce artifact download sizes?

**Comment by mostynb** [comment]
Hi, I'm not quite sure what you mean- what would client and server use as the baseline for the diff? I guess the client would need to select a candidate baseline, and check if the server has a copy of it, then either request or upload a binary diff blob using a new API.

If you're interested in pursuing this, I think you should propose it in the remote execution apis group:
https://groups.google.com/forum/#!forum/remote-execution-apis
https://github.com/bazelbuild/remote-apis/

**Comment by mostynb** [comment]
BTW the monthly remote execution api working group meeting is at 4pm Swedish time today. If you join the google group linked above you should automatically receive an invitation.

Closing this issue, but please @ me if you open a corresponding issue in the remote-apis repository.

**Comment by michaeleisel** [comment]
Sounds good
