### ISSUE TITLE
the dockerhub image needs to be updated

### ISSUE THREAD

**Issue by vors** [buchgr/bazel-remote#275]
https://github.com/buchgr/bazel-remote#useful-endpoints says that `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` should always be available.

## Repro

`docker run -v /path/to/cache/dir:/data -p 9090:8080 -p 9092:9092 buchgr/bazel-remote-cache`

`curl --head --fail http://localhost:9090/cas/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

## Expected

200

## Actual

`curl: (22) The requested URL returned error: 404 Not Found`

## Notes

```
> bazel-remote % curl http://localhost:9090/status

{
 "CurrSize": 0,
 "MaxSize": 5368709120,
 "NumFiles": 0,
 "ServerTime": 1589589764,
 "GitCommit": "ae546fc99a1bd7addd63269879e634545cdfcc1b"
}
`

**Comment by vors** [comment]
FWIW, I just tried building from master locally and this problem is fixed already.
I will leave the issue open as an indication that docker image needs to be updated. Please feel free to close it.

**Comment by mostynb** [comment]
Right- sorry about that. I will leave this open until @buchgr is able to update dockerhub.

**Comment by buchgr** [comment]
Done. Pushed master and v1.1.0. 

Thanks @vors and @mostynb !
