### ISSUE TITLE
Use symlinked Action Cache in ramdisk

### ISSUE THREAD

**Issue by mihaigalos** [buchgr/bazel-remote#285]
Would using an acttion cache in a ramdisk imrove lookup time when using the bazel remote cache?
I have tried to test this but seems spinning up the docker container fails with the message below.

I tried creating a ramdisk and moving the  `ac` into it, then symlinking to the `ac` where the cache is stored:
```bash
➜  /bazel_cache  ll                                                                                                                                                                                        total 28K
lrwxrwxrwx   1 root root   27 Jun  2 13:53 ac -> /mnt/ramdisk/bazel_cache/ac
drwxr-xr-x 258 root root 4,0K Feb  4 15:17 cas
drwx------   2 root root  16K Feb  4 15:06 lost+found
drwxr-xr-x 258 root root 4,0K Feb  4 15:17 raw
```

When I try to run the docker image, I get a `mkdir /data/ac: file exists` exception.
```bash
➜  /bazel_cache  docker run --rm --log-opt max-size=10m -v /bazel_cache:/data -p 9090:8080 -p 6060:6060 buchgr/bazel-remote-cache --ax_size=17
2020/06/02 11:36:23 bazel-remote built with go1.13.8 from git commit ae546fc99a1bd7addd63269879e634545cdfcc1b.
2020/06/02 11:36:23 Initial RLIMIT_NOFILE cur: 1048576 max: 1048576
2020/06/02 11:36:23 Setting RLIMIT_NOFILE cur: 1048576 max: 1048576
2020/06/02 11:36:23 mkdir /data/ac: file exists
```
I assume the implementation [here](https://github.com/buchgr/bazel-remote/blob/db9081195d0cc735213add5291fed61d5b5e584e/cache/disk/disk.go#L78) does not accept existing folders as symlinks.

**Comment by mostynb** [comment]
> Would using an acttion cache in a ramdisk imrove lookup time when using the bazel remote cache?

This would not help the "lookup" since we already use an in-memory index. It might improve the actual download since reading from a ramdisk has lower latency than reading from SSD (and much more than reading from HDD). However it is not clear if this will help much in practice, since the cost of the network traffic is much higher than the SSD latency. Benchmarks would be welcome, of course.

> ac -> /mnt/ramdisk/bazel_cache/ac
...
> When I try to run the docker image, I get a mkdir /data/ac: file exists exception.

I think the problem might be that your symlink target is an absolute path outside the docker container, but bazel-remote runs inside the container and does not see the target dir. Can you either try mapping that path into the docker container, or using bind mount in the host system instead of a symlink?

**Comment by mihaigalos** [comment]
> However it is not clear if this will help much in practice, since the cost of the network traffic is much higher than the SSD latency.

We are using the remote cache in a production environment and cosistenly seeing at least 3k+ sockets on baremetal and 10k+ sockets on VMs with up to 750MB/s (Megabytes/s!). 
The baremetal is obviously where we observe the bottlenec, since we're just using a generic ssd and gigabit ethernet as opposed to NVME and 10 GigE in the cloud.

As it turns out, there are a lot of possible bottlenecks:
* the network badwith, as you mentioned.
* the number of sockets.
* the buffer size and seek time to/from the ssd.

> I think the problem might be that your symlink target is an absolute path outside the docker container.

True, this is most likely the root cause. I'll look at it again tormorrow. Thank you!

**Comment by mihaigalos** [comment]
OK, so we had a look at it again, this time also mounting the ramdisk:
```bash
➜  /bazel_cache  docker run --rm --log-opt max-size=10m -v /bazel_cache:/data -v /mnt/ramdisk:/mnt/ramdisk -p 9090:8080 -p 6060:6060 buchgr/bazel-remote-cache --max_size=17
2020/06/03 09:08:24 bazel-remote built with go1.13.8 from git commit ae546fc99a1bd7addd63269879e634545cdfcc1b.
2020/06/03 09:08:24 Initial RLIMIT_NOFILE cur: 1048576 max: 1048576
2020/06/03 09:08:24 Setting RLIMIT_NOFILE cur: 1048576 max: 1048576
2020/06/03 09:08:24 Migrating files (if any) to new directory structure: /data/ac
2020/06/03 09:08:24 Attempting to migrate the old directory structure to the new structure failed with error: rename /data/ac /data/ac/ac: file exists
```

It appears that the [implementation](https://github.com/buchgr/bazel-remote/blob/db9081195d0cc735213add5291fed61d5b5e584e/cache/disk/disk.go#L190) does not skip past symlinks. Is this correct? How would we tackle this best?

**Comment by mostynb** [comment]
> It appears that the implementation does not skip past symlinks. Is this correct? How would we tackle this best?

That code should be fixed to handle symlinks. To run your test in the meantime, can you try mounting the ramdisk at `/bazel_cache/ac/` ?

**Comment by mihaigalos** [comment]
works using mounting the ramdisk to `/data/ac`. Thank you.
So using symlinks out-of the box sounds like a feature request, doesn't it? :)

**Comment by mostynb** [comment]
> works using mounting the ramdisk to /data/ac. Thank you.

Great- I look forward to seeing some benchmark numbers :)

> So using symlinks out-of the box sounds like a feature request, doesn't it? :)

Yes, I will fix it (unless you would like to).

**Comment by mihaigalos** [comment]
> Great- I look forward to seeing some benchmark numbers :)

I'm using a `Samsung EVO 860 2TB` with 500-1k sockets and 20-40MB/s constant traffic.
First benchmark is inconclusive. I could not see a major improvement by moving the `ac` into RAM.
Busy IO slowly ramps up and eventually saturates. I can see it ramping up quicker with no ramdisk than using the ramdisk, but I cannot tell if this is due to traffic or actual speed improvement I get from the ramdisk.

> Yes, I will fix it (unless you would like to).

Unfortunately I don't have time to and I don't need this feature this urgently to have to implement it.
Besides, the docker mount of the ramdisk fulfills my usecase. :+1:
