### ISSUE TITLE
Purging design

### ISSUE THREAD

**Issue by nicolov** [buchgr/bazel-remote#29]
I _think_ there are some bugs in EnsureSpacer, as my disks keep filling up. Anyways, I've been reading the code and I don't understand why it uses the low/high water marks to trigger deletion. We could store and update the atimes in `cache.files`, and ensure that there's enough space before each upload, instead of doing it in bulk once the cache goes over the high water mark. This would ensure optimal disk usage.

**Comment by buchgr** [comment]
> I think there are some bugs in EnsureSpacer, as my disks keep filling up.

I can totally believe that :-).

> Anyways, I've been reading the code and I don't understand why it uses the low/high water marks to trigger deletion.

The idea for the high watermark is to trigger deletion before the maximum cache size limit is reached, with only one upload being blocked by the deletion and other uploads proceeding. I don't know whether that works out well in practice. The idea for the low watermark is to only purge files to that limit as to keep recent outputs cached.

> We could store and update the atimes in cache.files, 

Oh yes! I wanted to do this for a while, as to not depend on filesystem `atime` anymore.

>  and ensure that there's enough space before each upload, instead of doing it in bulk once the cache goes over the high water mark. 

How do you know the size of an upload before the upload? We could use `Expect` headers but that would be a change to the caching protocol.

**Comment by nicolov** [comment]
I was thinking that the user would provide two numbers: the maximum overall
size of the cache, and the space that should be kept free for new uploads.
We could have a default of, say, 10GB for the latter. If you’re trying to
upload 10GB, you probably know what you’re doing.

We have a classic LRU with map + linked list sorted by atimes. Before
accepting a new upload, we make sure there’s enough space by deleting
elements from the back of the list.

This will add some latency to each individual upload, but will get rid of
the expensive purging step, and ensure max disk utilization at all times.

In this scheme, we would not be storing the atimes, just encoding them in
the sort order of the list. We would still need to read from the file
system when loading an existing directory.

What do you think?

**Comment by buchgr** [comment]
Yeah that sounds perfectly fine to me. Would you want to implement this?

I think making a best effort attempt to get the atime when loading an existing directory is fine, but it should still work even if atime is not supported.

**Comment by buchgr** [comment]
So you would still trigger deletion when `TotalSpace - UsedSpace < KeepFreeForUploadsSpace`? This is effectively what the high watermark is right now. I do think it's a good idea if you make this a function of the total cache size as it's currently. What's an argument for making this a fixed value?

The LRU design sounds good to me. I am not too worried about the additional latency as deletion is typically very fast.

I agree that we should try to use the `atime` when starting the server but in case the filesystem does not support it it should still work. Wdyt?

Would you want to implement this?

**Comment by nicolov** [comment]
I want to reserve a fixed amount of space, rather than a percentage,
because it’s linked to the amount of uploads that can be in flight at the
same time, not to the total size of the cache. If I upgrade my disk from
100 to 200GB, there’s no need to increase the amount of reserved space.
With a 1gig connection, it would take time to fill up a 10gig buffer anyway.

Why are you worried about atime? Have you found systems where it’s not
supported?

**Comment by buchgr** [comment]
Good point. I am wondering whether we should reserve space for uploads at all. Instead, we could:

1. Retrieve the expect size from the `Content-Length` header before reading the bytes from the network. 
2. Check if there's enough space available, if not make space available.
3. Reserve the space for the new upload from the available space
4. Read the bytes and store them on disk

I think that should work and we don't need to set aside extra space for uploads and ultimately avoid introducing another configuration option. What do you think?

> Why are you worried about atime? Have you found systems where it’s not
supported?

Afaik there's quite a few linux distros who have it disabled by default and/or mount their filesystems with `realtime` instead of `atime` (Ubuntu does this).

**Comment by nicolov** [comment]
Yes, that's more or less how I was thinking about this. The user caps the maximum size, and we make space for each new item. FS atime would only be used when loading an existing cache. If it's not available, the initial state of the eviction list would just be wrong, no big deal.

**Comment by nicolov** [comment]
I finally created a PR for this: https://github.com/buchgr/bazel-remote/pull/36

**Comment by nicolov** [comment]
Closing now that #36 is merged.

**Comment by buchgr** [comment]
Thanks again @nicolov
