### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by mmikitka** [buchgr/bazel-remote#302]
I want to run the bazel-remote container in a Kubernetes cluster constrained by a mandatory non-root Pod Security Policy rule. At present, bazel-remote is invoked as the root user.

A forthcoming PR will:
* Create the "bazelremote" user
* Create the "/data" directory
* Run the container as "bazelremote"

**Comment by mmikitka** [comment]
Here is the PR: https://github.com/buchgr/bazel-remote/pull/303

**Comment by mostynb** [comment]
Landed #303.
