### ISSUE TITLE
Remote Asset API - null hash failures for unrecognised extensions

### ISSUE THREAD

**Issue by simonpetty** [buchgr/bazel-remote#310]
I'm just exploring the use of this in our CI pipeline hosted in GCP.

If i run the docker image locally...
`docker run -v ~/bazel-cache:/data -p 9092:9092 buchgr/bazel-remote-cache --experimental_remote_asset_api --max_size 40 --disable_grpc_ac_deps_check`

...then run a bazel build against it locally...
`bazel build --experimental_remote_downloader=grpc://localhost:9092 --remote_cache=grpc://localhost:9092 --remote_timeout=120 --verbose_failures --record_rule_instantiation_callstack //...`

...this works fine.

But if i try exactly the same thing, but with the docker image running on a GCP compute instance, and run bazel from Cloud Build (at the moment using the external IP of the instance), i get the following error:

> INFO: Repository go_puller_darwin instantiated at:
  /workspace/WORKSPACE:23:1: in <toplevel>
  /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_docker/repositories/repositories.bzl:44:9: in repositories
Repository rule http_file defined at:
  /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl:426:13: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_puller_darwin':
   com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted 34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad

I'm aware that the Remote Asset API is experimental, but since it works locally i'm guessing it's not that.

Bazel and gRPC are relatively new to me, but it seems like it's pointing towards some network packet corruption?

Anyway, are there any tips for how i could look to investigate this?

**Comment by mostynb** [comment]
> `Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted ...`

This is the first thing that jumps out at me- this is the null sha256 hash.

Do you have the logs from bazel-remote? And can you find the corresponding http_archive rule from your WORKSPACE file for `34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad` ?

**Comment by simonpetty** [comment]
Thanks for replying. Good spot on the null sha256 hash.

It's trying to get a dependency of rules_docker called go_puller_darwin:

> http_file(
            name = "go_puller_darwin",
            executable = True,
            sha256 = "34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad",
            urls = [("https://storage.googleapis.com/rules_docker/" + RULES_DOCKER_GO_BINARY_RELEASE + "/puller-darwin-amd64")],
        )

Taken from here:
https://github.com/bazelbuild/rules_docker/blob/v0.14.1/repositories/repositories.bzl

Logs from bazel-remote (is there a way to enable more verbose logging?):

> 2020/07/14 08:47:46 GRPC GETCAPABILITIES
2020/07/14 08:47:47 GRPC BYTESTREAM READ COMPLETED blobs/dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250/557250
2020/07/14 08:47:51 GRPC BYTESTREAM READ COMPLETED blobs/cad0b49c525c5289af7031beab4c54e029c4ac231720ccb0163f800fc0100b3c/866452
2020/07/14 08:47:54 GRPC BYTESTREAM READ COMPLETED blobs/e5d90f0ec952883d56747b7604e2a15ee36e288bb556c3d0ed33e818a4d971f2/78265
2020/07/14 08:47:55 GRPC BYTESTREAM READ COMPLETED blobs/7fc87f4170011201b1690326e8c16c5d802836e3a0d617d8f75c3af2b23180c4/1494738
2020/07/14 08:47:58 GRPC BYTESTREAM READ COMPLETED blobs/b27e55d2dcc9e6020e17614ae6e0374818a3e3ce6f2024036e688ada24110444/425817
2020/07/14 08:47:59 GRPC BYTESTREAM READ COMPLETED blobs/79c9850690d7614ecdb72d68394f994fef7534b292c4867ce5e7dec0aa7bdfad/182649
2020/07/14 08:48:14 GRPC BYTESTREAM READ COMPLETED blobs/0585dd18b120874de6dea56041e0b1db800847a72d3cac1cbffdbba5150d4cc0/23493
2020/07/14 08:48:14 GRPC BYTESTREAM READ COMPLETED blobs/0869fca5993ce9bbfe854e68076ba4b7b5d2ba8d151e4dcc565d85d23881b8d6/43907
2020/07/14 08:48:16 GRPC BYTESTREAM READ COMPLETED blobs/84abf7ac4234a70924628baa9a73a5a5cbad944c4358cf9abdb4aab29c9a5b77/981936
2020/07/14 08:48:20 GRPC BYTESTREAM READ COMPLETED blobs/66184688debeeefcc2a16a2f80b03f514deac8346fe888fb7e691a52c023dd88/9876
2020/07/14 08:48:21 GRPC BYTESTREAM READ COMPLETED blobs/bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598/9422
2020/07/14 08:48:45 GRPC BYTESTREAM READ COMPLETED blobs/a1bc06deb070155c4f67c579f896a45eeda5a8fa54f35ba233304074c4abbbbd/120081829

Thanks for the help

**Comment by mostynb** [comment]
No problem.

Here's a test branch which logs the outgoing requests, and recognises failed-but-nonerror fetches (this missing check probably explains the null sha256 hash):
https://github.com/mostynb/bazel-remote/commits/remote_asset_fetch_error_handling

Can you try that on GCP?

**Comment by simonpetty** [comment]
I didn't see your new log line unfortunately. Verified it was using that commit:
`2020/07/14 11:10:30 bazel-remote built with go1.14.3 from git commit 7a093f3110e6b1ca82415a6745ec5778e96e9586.`

It just output the same ` GRPC BYTESTREAM READ COMPLETED` lines

**Comment by mostynb** [comment]
I think you will need to clear bazel's local cache- otherwise it won't need to ask bazel-remote for these items. Try `bazel clean` before running your test.

**Comment by simonpetty** [comment]
Thanks, i should have thought of that. Here's the output:

> 2020/07/14 11:58:09 GRPC GETCAPABILITIES
2020/07/14 11:58:11 GRPC ASSET FETCH https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz 200 OK
2020/07/14 11:58:11 GRPC BYTESTREAM READ COMPLETED blobs/dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250/557250
2020/07/14 11:58:13 GRPC ASSET FETCH https://github.com/bazelbuild/rules_scala/archive/d367bdbf03ff594de62eb6c28725716b74aca5f4.zip 200 OK
2020/07/14 11:58:14 GRPC BYTESTREAM READ COMPLETED blobs/cad0b49c525c5289af7031beab4c54e029c4ac231720ccb0163f800fc0100b3c/866452
2020/07/14 11:58:15 GRPC ASSET FETCH https://github.com/bazelbuild/bazel-skylib/archive/1.0.2.tar.gz 200 OK
2020/07/14 11:58:15 GRPC BYTESTREAM READ COMPLETED blobs/e5d90f0ec952883d56747b7604e2a15ee36e288bb556c3d0ed33e818a4d971f2/78265
2020/07/14 11:58:16 GRPC ASSET FETCH https://github.com/bazelbuild/bazel-gazelle/releases/download/0.18.2/bazel-gazelle-0.18.2.tar.gz 200 OK
2020/07/14 11:58:17 GRPC BYTESTREAM READ COMPLETED blobs/7fc87f4170011201b1690326e8c16c5d802836e3a0d617d8f75c3af2b23180c4/1494738
2020/07/14 11:58:18 GRPC ASSET FETCH https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.21.0/rules_go-v0.21.0.tar.gz 200 OK
2020/07/14 11:58:18 GRPC BYTESTREAM READ COMPLETED blobs/b27e55d2dcc9e6020e17614ae6e0374818a3e3ce6f2024036e688ada24110444/425817
2020/07/14 11:58:19 GRPC ASSET FETCH https://github.com/bazelbuild/rules_jvm_external/archive/2.8.zip 200 OK
2020/07/14 11:58:19 GRPC BYTESTREAM READ COMPLETED blobs/79c9850690d7614ecdb72d68394f994fef7534b292c4867ce5e7dec0aa7bdfad/182649
2020/07/14 11:58:34 GRPC ASSET FETCH https://github.com/atlassian/bazel-tools/archive/46c2595f1dfc50a8c5f22b51dd8a33a3bbe23287.tar.gz 200 OK
2020/07/14 11:58:34 GRPC BYTESTREAM READ COMPLETED blobs/0585dd18b120874de6dea56041e0b1db800847a72d3cac1cbffdbba5150d4cc0/23493
2020/07/14 11:58:35 GRPC ASSET FETCH https://github.com/lucidsoftware/rules_twirl/archive/a2aade10636b20fe50413b8f8eb5a311091372ec.zip 200 OK
2020/07/14 11:58:35 GRPC BYTESTREAM READ COMPLETED blobs/0869fca5993ce9bbfe854e68076ba4b7b5d2ba8d151e4dcc565d85d23881b8d6/43907
2020/07/14 11:58:38 GRPC ASSET FETCH https://github.com/bazelbuild/rules_nodejs/releases/download/1.7.0/rules_nodejs-1.7.0.tar.gz 200 OK
2020/07/14 11:58:38 GRPC BYTESTREAM READ COMPLETED blobs/84abf7ac4234a70924628baa9a73a5a5cbad944c4358cf9abdb4aab29c9a5b77/981936
2020/07/14 11:58:42 GRPC ASSET FETCH https://mirror.bazel.build/github.com/bazelbuild/platforms/archive/46993efdd33b73649796c5fc5c9efb193ae19d51.zip 200 OK
2020/07/14 11:58:42 GRPC BYTESTREAM READ COMPLETED blobs/66184688debeeefcc2a16a2f80b03f514deac8346fe888fb7e691a52c023dd88/9876
2020/07/14 11:58:42 GRPC ASSET FETCH https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip 200 OK
2020/07/14 11:58:43 GRPC BYTESTREAM READ COMPLETED blobs/bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598/9422
2020/07/14 11:58:43 GRPC ASSET FETCH https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz 200 OK
2020/07/14 11:59:17 GRPC BYTESTREAM READ COMPLETED blobs/a1bc06deb070155c4f67c579f896a45eeda5a8fa54f35ba233304074c4abbbbd/120081829

In case it's useful have included more of the client side logs:

> INFO: Repository go_puller_darwin instantiated at:
  /workspace/WORKSPACE:23:1: in <toplevel>
  /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_docker/repositories/repositories.bzl:44:9: in repositories
Repository rule http_file defined at:
  /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl:426:13: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_puller_darwin':
   com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted 34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad
ERROR: /workspace/balance/balance-service/BUILD:3:1: no such package '@java_image_base//image': no such package '@go_puller_darwin//file': com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted 34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad and referenced by '//balance/balance-service:image'
ERROR: Analysis of target '//balance/balance-service:image' failed; build aborted: no such package '@java_image_base//image': no such package '@go_puller_darwin//file': com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted 34aa3e299c806ce59a012bd1b3a245e25807988e5475189d2edc075163b47dad
INFO: Elapsed time: 80.573s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (21 packages loaded, 103 targets configured)
FAILED: Build did NOT complete successfully (21 packages loaded, 103 targets configured)
ERROR
ERROR: build step 0 "gcr.io/cloud-marketplace-containers/google/bazel:3.1.0" failed: step exited with non-zero status: 1

**Comment by mostynb** [comment]
I think I figured it out, pushed a new commit to the branch with a potential fix:
https://github.com/mostynb/bazel-remote/commit/6825a97d608a0d420e92303b4e4ec2ce928b5c35

**Comment by simonpetty** [comment]
Yep, that's done the trick!

**Comment by mostynb** [comment]
Thanks for confirming. I will clean this up and land it soon.

This is also partially a bug on the bazel side- IIUC the null hash came from bazel hashing the unset/empty array in the "NotFound" result. I will follow this up too.
