### ISSUE TITLE
flags should override environment variables

### ISSUE THREAD

**Issue by brown** [buchgr/bazel-remote#319]
When I run 

BAZEL_REMOTE_PORT=foo bazel-remote --port bar

I expect an error message that mentions "bar".  Instead, I get a message about "foo".

Command line arguments should override environment variables when configuring bazel remote.
This bit me when running bazel remote on Kubernetes.  I specified the configuration using flags,
but the binary took some configuration info from the environment, overriding my flag settings.
Ideally, you should remove the ability to configure bazel remote using environment variables.  If
environment variables can be set, flags can be passed to the binary.  There's no reason to offer
both ways to configure a server.

**Comment by mostynb** [comment]
Hi.

Are you sure that the environment overrode your command line flags? If I provide both a valid environment variable and command line arg, eg:
`BAZEL_REMOTE_PORT=1111 ./bazel-remote --port 1112 --dir testdir --max_size 1`

Then I can see the port specified in the command line args in the startup log:
`2020/07/23 12:39:04 Starting HTTP server on address :1112`

**Comment by mostynb** [comment]
This seems like a "feature" of the command line argument parsing library that bazel-remote uses (github.com/urfave/cli), ie that it parses all existing sources of a flag even if they're overridden. We can't remove environment variable support from bazel-remote without breaking existing users, so we will need to keep them.

However, I did file an issue with to make the error message from the command line arg parsing library state where the value was obtained: https://github.com/urfave/cli/issues/1167, which would at least help you figure out the real issue more easily.
