### ISSUE TITLE
discussion: should we verify the hash in the CAS?

### ISSUE THREAD

**Issue by buchgr** [buchgr/bazel-remote#32]
I am not convinced that we the remote cache should verify the hash sum of CAS entries, in that it costs significant processing power and it's not clear that it helps with anything :-). Wdyt @nicolov?

**Comment by nicolov** [comment]
From my testing, I think we can keep it. On AWS, paying for > 1gbit bandwidth also gets you an obscene amount of CPU power, so it's not a problem. On desktop machines, the 1gbit network will be a bottleneck before the hashing is. Besides, you'd expect the load to be mostly read-only anyways, or your disks will fill up quickly.
