### ISSUE TITLE
Support for mTLS

### ISSUE THREAD

**Issue by SecurityInsanity** [buchgr/bazel-remote#356]
Currently it looks like bazel-remote does not have support for mTLS, even though the underlying gRPC library has support for it. Would you be open to a PR adding in support for specifying a `--tlsCaFile`, and enforcing client mTLS if that flag is specified along with cert/key?

**Comment by SecurityInsanity** [comment]
Hey @mostynb ,

Thanks for the quick reply!

mTLS (mutual tls may be easier if searching) is where the client presents a certificate, and the server validates it is signed by a trusted source. Effectively a form of authentication (though not authorization).

The use case is to allow a cache that is open on the web, but not have it so just anyone can access it. We'd like to use S3 as a cache source without having to have people get a new password for just accessing the cache (and all of our developers already have certificates, so it would plug in nicely).

As for clients, anything really that can use TLS most likely has some level of support for mTLS. gRPC has full support for mTLS, as does curl, many HTTP Libs, and even bazel allows accessing the remote cache with a client certificate: https://github.com/bazelbuild/bazel/pull/11030 .

I'd assume anything that can talk to the cache now most likely has an option for using mTLS, though even if there are a few that aren't they can't just not pass in `--tlsCaFile`, and should continue using the cache as normally.

**Comment by mostynb** [comment]
Thanks for the explanation. I'm not sure that I would personally expose bazel-remote on the open internet, but this feature would be useful even on some private networks. Please go ahead and submit a PR :)
