### ISSUE TITLE
make 1.3.0 release

### ISSUE THREAD

**Issue by mostynb** [buchgr/bazel-remote#378]
The allow-concurrent-writes refactoring seems to have stuck. Time for a new release.

**Comment by mostynb** [comment]
@buchgr: when you get a chance, could you please update the dockerhub image using the v1.3.0 tag?

**Comment by buchgr** [comment]
done. @mostynb I realized that I don't have your e-mail address. Can you please reach out to me at buchgr at google dot com. Thanks!
