### ISSUE TITLE
Does not work for ARM devices

### ISSUE THREAD

**Issue by prestonvanloon** [buchgr/bazel-remote#38]
Attempting this on Raspberry Pi 3

Command: `docker run -v /tmp/bazel-cache-data:/data -p 9090:80 buchgr/bazel-remote-cache`

Result:
```
standard_init_linux.go:190: exec user process caused "exec format error"
```

**Comment by nicolov** [comment]
The docker image only works on intel CPUs. You can tweak linux-build.sh to
build for ARM instead.

**Comment by prestonvanloon** [comment]
I created this issue with the hope that it would be a trivial fix. I think this project would need to create images specifically for each architecture. 

I'd like to run a bazel remote cache with one of my extra raspberry pis but I understand if this request is a bit out of scope for this project. I can build my own docker image to satisfy use case with something like https://github.com/dockcross/dockcross

**Comment by buchgr** [comment]
I would be happy to include a Dockerfile for ARM if you were to contribute one :-).

**Comment by mihaigalos** [comment]
PR [215](https://github.com/buchgr/bazel-remote/pull/215) should offer support for ARM architectures, making it possible to deploy a bazel remote cache server onto a i.e. Raspberry Pi.
