### ISSUE TITLE
Any s3 deployment examples

### ISSUE THREAD

**Issue by chenrui333** [buchgr/bazel-remote#383]
I was trying to get it up and running in my local to talk to s3 bucket, but somehow, I am not able to see the cache showing up in the S3 bucket.

```
docker run -u 1000:1000 -v ~/bazel-cache:/data \
  -p 9090:8080 -p 9092:9092 \
  buchgr/bazel-remote-cache --s3.endpoint=s3.us-east-1.amazonaws.com \
                            --s3.bucket=test-bucket \
                            --s3.prefix=test-prefix \
                            --s3.access_key_id=test \
                            --s3.secret_access_key="test" \
                            --s3.disable_ssl=true \
                            --s3.key_version="2" \
                            --max_size=100     
```

here is my bazelrc setting:
```
 build --remote_timeout=20
-build --remote_cache=https://bazel:baz3l@bazel-cache.blt.meetup.com
+build --remote_cache=http://localhost:9090
 build --remote_accept_cached=true
 build --remote_upload_local_results=true
 build --remote_local_fallback=true
```

I wonder what I did wrong. Thanks!

**Comment by mostynb** [comment]
Hi,

I don't have an AWS account to test this feature with myself, but this looks similar to the config described in cache/s3proxy/minio-test-setup.md that I test with.

Did you create "test-bucket" beforehand? And are there any warnings or errors in bazel-remote's logs when you test this?

**Comment by chenrui333** [comment]
yes, I created a test bucket, let me see the logs stuff

**Comment by mostynb** [comment]
@chenrui333: did you ever figure this out? I'd be happy to add documentation (or just references) on how to do this.
