### ISSUE TITLE
bazel-remote vs bazel-buildfarm comparison

### ISSUE THREAD

**Issue by slsyy** [buchgr/bazel-remote#392]
Looking at first glance a [bazel-buildfarm](https://github.com/bazelbuild/bazel-buildfarm) looks like a superset of a bazel-remote. Could you add some rationale why should I use the bazel-remote instead?

**Comment by mostynb** [comment]
You're right that bazel-buildfarm provides a superset of functionality that bazel-remote does. This is also the case for other remote execution services (eg https://github.com/buildbarn).

I'm not familiar with bazel-buildfarm's cache implementation so I can't give a direct comparison, but I suspect that bazel-remote is simpler to setup- it's a single statically linked binary with simple filesystem based storage. If you just want a cache, bazel-remote is really easy to get started with.

If you want remote execution, then I would recommend starting with a complete service like buildfarm/buildbarn. Some people use bazel-remote as part of these setups for various reasons, but I wouldn't start with that.

**Comment by kragniz** [comment]
@slsyy being only slightly facetious, I prefer operating as few JVMs as possible and only currently need a remote cache
