### ISSUE TITLE
Expose metrics via grpc

### ISSUE THREAD

**Issue by omarzl** [buchgr/bazel-remote#400]
Hello,

We are using the cache with http and we want to migrate to grpc, our devops team can't enable both for us, so we won't be able to send http requests to the /metrics endpoint, is it possible to get them using grpc? I am searching a way to but It think it is not possible right now

**Comment by mostynb** [comment]
Hi,

I'm not sure if it's possible to collect (prometheus) metrics from a gRPC endpoint without using http. Can't you just allow connections to both ports?

**Comment by omarzl** [comment]
Hello, I know this is kinda strange, but in our company everything is automatically deployed in aws infra based on an internal document that expects that all the docker images expose only one port /:

I am wrapping the /metrics endpoint via grpc, here is the pull request maybe someone find it useful too: https://github.com/buchgr/bazel-remote/pull/401

**Comment by mostynb** [comment]
I think this might be a little too specific to your unusual setup to merge.

If you don't want to maintain this as a local patch, maybe you could try implementing a proxy using something like https://github.com/mwitkow/grpc-proxy

**Comment by omarzl** [comment]
No problem, I will take a look to that option too, thanks!
