### ISSUE TITLE
Changing from v1.3.1 to v2.0.0 breaks builds with AWS S3 storage backend

### ISSUE THREAD

**Issue by lukedirtwalker** [buchgr/bazel-remote#420]
After the switch to version 2.0.0 of the bazel-remote image our builds started failing.
Example error from bazel:
```
(03:06:37) ERROR: An error occurred during the fetch of repository 'io_bazel_rules_go':
   Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2c5758fdd18438639bdb6a4b4f0b5e90/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid size (must be non-negative): -1
```
We use `--experimental_remote_asset_api`.

From the logs of the bazel-remote I don't get any more insights: (the log is
```
Using S3 backend.
2021/04/05 03:06:16 GRPC GETCAPABILITIES
2021/04/05 03:06:17 S3 CONTAINS buildkite-bazel-cache-anapaya cas.v2/ec/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d OK
2021/04/05 03:06:17 S3 DOWNLOAD buildkite-bazel-cache-anapaya cas.v2/ec/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d OK
2021/04/05 03:06:17 GRPC BYTESTREAM READ: Invalid size (must be non-negative): -1
2021/04/05 03:06:37 GRPC GETCAPABILITIES
2021/04/05 03:06:37 S3 DOWNLOAD buildkite-bazel-cache-anapaya cas.v2/ec/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d OK
2021/04/05 03:06:37 GRPC BYTESTREAM READ COMPLETED blobs/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d/9356
2021/04/05 03:06:37 S3 CONTAINS buildkite-bazel-cache-anapaya cas.v2/6f/6f111c57fd50baf5b8ee9d63024874dd2a014b069426156c55adbf6d3d22cb7b OK
2021/04/05 03:06:37 S3 DOWNLOAD buildkite-bazel-cache-anapaya cas.v2/6f/6f111c57fd50baf5b8ee9d63024874dd2a014b069426156c55adbf6d3d22cb7b OK
2021/04/05 03:06:37 GRPC BYTESTREAM READ: Invalid size (must be non-negative): -1
```

Any pointers in what I could look into, to figure out what the problem is?
Let me know if I can help it anyway to further debug this.

For now we just switched back to v1.3.1

**Comment by mostynb** [comment]
Hi, I suspect this is a bug when parsing the resource name from the bytestream read request, but the error logs don't show the resource name. I wonder if you could try using a build in the branch from https://github.com/buchgr/bazel-remote/pull/421 and paste the new error message here?

And could you also try to figure out which resource corresponds to the sha256 hash included in the read request- is it an "asset" hash that appears in your WORKSPACE file, or is it something else like the hash of one of the source files in your codebase?

**Comment by mostynb** [comment]
Added a potential fix to the PR: https://github.com/buchgr/bazel-remote/pull/421/commits/1cccbcff552441b6dff8b1bb13f1cb10fbca8241

**Comment by lukedirtwalker** [comment]
Thanks a lot for this quick reaction. I'll try it out first thing tomorrow.

**Comment by mostynb** [comment]
Reopening until the fix is verified.

**Comment by lukedirtwalker** [comment]
Okay I built the new image and tried to run it. It still seems to fail out:
Logs from image:
```
Using S3 backend.
2021/04/07 05:35:43 GRPC GETCAPABILITIES
2021/04/07 05:35:44 S3 CONTAINS buildkite-bazel-cache-anapaya cas.v2/ec/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d OK
2021/04/07 05:35:44 S3 DOWNLOAD buildkite-bazel-cache-anapaya cas.v2/ec/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d OK
2021/04/07 05:35:44 GRPC BYTESTREAM READ: Invalid size (must be non-negative): -1 from "blobs/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d/-1"
```
snippet from bazel output:
```
(05:35:44) Loading: 0 packages loaded
    Fetching @apple_rules_lint; fetching
(05:35:44) INFO: Repository apple_rules_lint instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/70271074a3502a131360185dc98c961a/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(05:35:44) Loading: 0 packages loaded
    Fetching @apple_rules_lint; fetching
(05:35:44) ERROR: An error occurred during the fetch of repository 'apple_rules_lint':
   Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/70271074a3502a131360185dc98c961a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid size (must be non-negative): -1 from "blobs/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d/-1"
(05:35:44) Loading: 0 packages loaded
(05:35:44) ERROR: no such package '@apple_rules_lint//lint': java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid size (must be non-negative): -1 from "blobs/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d/-1"
```
This is an asset from an http_archive:
```
# linter rules
http_archive(
    name = "apple_rules_lint",
    sha256 = "ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d",
    urls = [
        "https://github.com/apple/apple_rules_lint/releases/download/0.1.0/apple_rules_lint-0.1.0.tar.gz",
    ],
)
```

Note that we run with `--experimental_remote_asset_api`.

Anything more I can do to debug?

**Comment by lukedirtwalker** [comment]
One special thing about our setup is that we start a bazel-remote instance for each buildkite agent. So they will initially start with an empty disk cache and will proxy to the S3 backend.

**Comment by mostynb** [comment]
Just to confirm- which commit did you build + test with?

> `blobs/ece669d52998c7a0df2c2380f37edbf4ed8ebb1a03587ed1781dfbececef9b3d/-1`

This suggests that the client has provided an incorrect size. Since this is an "asset", I think the flow must have been:
1. Client calls `FetchBlob`
2. Server (incorrectly) responds with a `FetchBlobResponse` with a `Digest` with `SizeBytes` -1
3. Client makes a bytestream `Read` request with the invalid size

We'll need to focus on step 1. In `FetchBlob` there are two paths where we return a `Digest`, the first is when we get a cache hit and this checks that the size is non-negative. The second path attempts to download the item, add it to the cache and return its Digest (which includes the size) - I suspect the error is here. One way to debug this would be to add a panic in this second path if the size is negative, then trigger the bug and look through the stack trace to find where the value came from.

**Comment by lukedirtwalker** [comment]
> Just to confirm- which commit did you build + test with?
I used latest master, i.e. `1cccbcff552441b6dff8b1bb13f1cb10fbca8241`

I'll try to reproduce the error on my host and add the panic, so that I get more insight.

**Comment by lukedirtwalker** [comment]
I found the issue and have a fix in https://github.com/buchgr/bazel-remote/pull/422

What is not clear to me however, is why the S3 backend doesn't report the correct size here. We only set the size under certain circumstances:
https://github.com/buchgr/bazel-remote/blob/1cccbcff552441b6dff8b1bb13f1cb10fbca8241/cache/s3proxy/s3proxy.go#L254-L256
What is the reasoning behind this ^ ?

**Comment by mostynb** [comment]
Great- I will check the PR later this afternoon.

The reason that the size is not always known is because v2.0.0 introduced compressed CAS blob storage, which is enabled by default. When compressed storage is enabled, blobs are also stored compresed on proxy backends, and then we can't use the s3 object's reported size (since we need the size once uncompressed).
