### ISSUE TITLE
Manually PUT in cache via cURL

### ISSUE THREAD

**Issue by mihaigalos** [buchgr/bazel-remote#434]
I think it could be possible to manually add content to the remote cache via cURL.
I can't seem to make it work though, tried with the following:

```bash
$ curl -X PUT http://localhost:9090/ input.txt
```
Is there an easy way to generate both the AC and CAS entries?

**Comment by mostynb** [comment]
You need to specify ac/<sha256> or cas/<sha256> in the URL for this to work, eg:
`curl http://localhost:9090/cas/0f55225511fa29e9d1d46333d3dfa0a831b735d35b82548a3ee6ae5156fa6618 --upload-file blob`

I'm not sure of a simple way to create AC blobs without writing a small program though.
