### ISSUE TITLE
Reject/warn/monitor on large objects entering the cache

### ISSUE THREAD

**Issue by alexeagle** [buchgr/bazel-remote#440]
Our cache deployment has suffered badly from docker images being added by users as inputs to actions. Something like 600MB object then needs to get fetched by CI agents and it overloads the cache with requests.

I'm not exactly sure what the cache could do differently to help. At least showing the largest object, with some hint about the action that generated it.

The feedback loop would result in us making sure these targets are tagged `no-remote-cache` so the actions they produce don't upload.

**Comment by mostynb** [comment]
Hi,

In cache-only mode (ie without remote execution) the client doesn't upload actions to the cache server- the only information that the server could report is the sizes of the blobs and their sha256 hashes, and if it were to scan the entire cache lookup table it could report the lookup keys for ActionResult messages that refer to large blobs. But that would be slow and still be difficult to find the corresponding actions on the client side.

I suppose the cache server could choose to reject blobs over a certain size limit, but I think most clients would just log a warning and continue, and then the cache hit rate would drop until someone notices. So this wouldn't be a great solution either.

Perhaps this is best solved on the client side? I don't know if bazel has a way to do this.

**Comment by alexeagle** [comment]
thanks for the reply @mostynb . That makes sense, I agree that Bazel is the more likely place to make such a feature.

**Comment by alexeagle** [comment]
Based on discussion on that linked Bazel issue I think this is actually a desirable feature.

@mostynb would you accept a PR adding a flag to reject large WriteResource requests, basically in this spot https://gist.github.com/alexeagle/71d39f470ba45c7f8a7fcc38a70bfd8c ?
