### ISSUE TITLE
Is there a goroutine leak?

### ISSUE THREAD

**Issue by timmyhu** [buchgr/bazel-remote#444]
Hi, 
From the point of view of our application of monitoring diagram, it seems that there is a  goroutine leak. The goroutines only increases, but don't decrease, and memory also keeps increasing.  

My bazel-remote version is 1.3.1, and the grpc_stream.go(line 300) is suspected, but it seam that maybe the newest version has just this problem also.

![image](https://user-images.githubusercontent.com/28779863/120466358-8ca2e900-c3d1-11eb-86cc-7fd0aca7fc94.png)

**Comment by mostynb** [comment]
I think I might have figured out the issue, here's a possible fix: #445.

**Comment by timmyhu** [comment]
thanks @mostynb ,it seams that this may be fixed, we will try it.

**Comment by mostynb** [comment]
Thanks- if it looks good I will backport it and make a 1.3.2 release also.

**Comment by timmyhu** [comment]
@mostynb  it looks good so far, i'm waitting for it to run for futher while.

**Comment by timmyhu** [comment]
@mostynb 

After a few days of monitoring and observation, it looks very well now, and there is no leakage, thanks @mostynb  for your quick and efficient solution haha.
