### ISSUE TITLE
Push linux arm64 docker images to dockerhub

### ISSUE THREAD

**Issue by mostynb** [buchgr/bazel-remote#450]
@MaciejKucia asked if we could push (linux) arm64 images to dockerhub too.
https://github.com/buchgr/bazel-remote/issues/163#issuecomment-868271393

**Comment by mostynb** [comment]
It looks like rules_docker doesn't support pushing multiple os/arch images to the same tag on dockerhub: https://github.com/bazelbuild/rules_docker/issues/1599

**Comment by mostynb** [comment]
I think I figured out how to do this externally from bazel, the latest tag on docker hub now has both amd64 and arm64 images.

**Comment by MaciejKucia** [comment]
Splendid, thank you!
