### ISSUE TITLE
crash because running out of threads

### ISSUE THREAD

**Issue by Yannic** [buchgr/bazel-remote#479]
I'm running the latest release, downloaded from GitHub:

```
2021/09/30 10:15:05 bazel-remote built with go1.16 from git commit 400101af9d14bae5fb400b80b8dbd279b4b30075.
```

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0xd30c52, 0x11)
	GOROOT/src/runtime/panic.go:1117 +0x72
runtime.checkmcount()
	GOROOT/src/runtime/proc.go:701 +0xac
runtime.mReserveID(0x12d9e38)
	GOROOT/src/runtime/proc.go:717 +0x3e
runtime.startm(0xc000044800, 0x445b00)
	GOROOT/src/runtime/proc.go:2326 +0x92
runtime.handoffp(0xc000044800)
	GOROOT/src/runtime/proc.go:2368 +0x65
runtime.retake(0x23bc9b0957b412, 0x1)
	GOROOT/src/runtime/proc.go:5322 +0x17d
runtime.sysmon()
	GOROOT/src/runtime/proc.go:5230 +0x185
runtime.mstart1()
	GOROOT/src/runtime/proc.go:1306 +0xc8
runtime.mstart()
	GOROOT/src/runtime/proc.go:1272 +0x6e

goroutine 1 [IO wait, 1432 minutes]:
internal/poll.runtime_pollWait(0x7f39b21c9f98, 0x72, 0x0)
	GOROOT/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000a0f98, 0x72, 0x0, 0x0, 0xd286e9)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000a0f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0000a0f80, 0x30, 0x30, 0x7f39d8e4c5b8)
	GOROOT/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0b4567848, 0xc05223d5d8, 0x40e278, 0x30)
	GOROOT/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0b4567848, 0xcb2dc0, 0xc0b456d140, 0xc1b900, 0x12bd620)
	GOROOT/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00027c380, 0xe2af30, 0xc0b4567848, 0x0, 0x0)
	GOROOT/src/net/http/server.go:2981 +0x285
net/http.(*Server).ListenAndServe(0xc00027c380, 0x2, 0x2)
	GOROOT/src/net/http/server.go:2910 +0xba
main.main.func1(0xc0002fd240, 0x0, 0x40)
	main.go:542 +0xdeb
github.com/urfave/cli/v2.(*App).RunContext(0xc000106c00, 0xe2ce28, 0xc000034068, 0xc00010c000, 0x9, 0x9, 0x0, 0x0)
	external/com_github_urfave_cli_v2/app.go:315 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:215
main.main()
	main.go:545 +0x1b06

goroutine 28 [IO wait]:
internal/poll.runtime_pollWait(0x7f39b21c9eb0, 0x72, 0x0)
	GOROOT/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000a1018, 0x72, 0x0, 0x0, 0xd286e9)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000a1000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0000a1000, 0x37e11d600, 0x0, 0x0)
	GOROOT/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0b4567860, 0xc0b4604c40, 0xc0b4604c48, 0x18)
	GOROOT/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0b4567860, 0xd67420, 0xc0001ff6c0, 0xe33f90, 0xc00f2d0898)
	GOROOT/src/net/tcpsock.go:261 +0x65
google.golang.org/grpc.(*Server).Serve(0xc0001ff6c0, 0xe2af30, 0xc0b4567860, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:704 +0x27f
github.com/buchgr/bazel-remote/server.serveGRPC(0xe2af30, 0xc0b4567860, 0xc0001145c0, 0x2, 0x2, 0xc0b4000001, 0xc000302a20, 0xe1e760, 0xc000388190, 0xe1e760, ...)
	server/grpc.go:80 +0x1c6
github.com/buchgr/bazel-remote/server.ListenAndServeGRPC(0xc0000342f0, 0x5, 0xc0001145c0, 0x2, 0x2, 0xc000000001, 0xc000302a20, 0xe1e760, 0xc000388190, 0xe1e760, ...)
	server/grpc.go:58 +0x125
main.main.func1.2(0xc00016ec00, 0x0, 0x0, 0x0, 0xc000302a20, 0xc000388190, 0xc0003881e0)
	main.go:502 +0x51e
created by main.main.func1
	main.go:454 +0xc5c

...
```

Full logs: [logs.zip](https://github.com/buchgr/bazel-remote/files/7258714/logs.zip)

**Comment by mostynb** [comment]
Thanks for the bug report- could you share the config/command line (minus any passwords)? What kind of storage are you using (SSD/HDD/)? And just to confirm, is this v2.1.4?

**Comment by mostynb** [comment]
Ahh wait, it looks like you're running v1.3.3 which is rather old. I think it has newer (cherry-picked) commits than the latest release, v2.1.4, and github unhelpfully shows v1.3.3 as "latest".

Can you try v2.1.4 and see if it has the same issue?

**Comment by Yannic** [comment]
Oh, thanks GitHub...

Will try v2.1.4 and report back in a few days, it takes a while to repro this.

**Comment by Yannic** [comment]
v2.1.4 crashes on startup :(

Logs: [logs_v2.1.4.zip](https://github.com/buchgr/bazel-remote/files/7259505/logs_v2.1.4.zip)

**Comment by mostynb** [comment]
Hmm while building the LRU index it's evicting a lot of files at once (9999), and hits the default 10k operating system thread limit. Each removeFile function call is called in its own goroutine, because I was not expecting this to happen so often all at once.

Did you create a large cache previously (more than 1T), and now start bazel remote with a 1T size limit? I will add some code to handle this better, but in the meantime as a quick workaround, you could either just remove the cache dir manually and start over. Or you could try to put together a bash script to sort the files in the cache dir by atime and remove the oldest ones until the cache size is closer to the new 1T limit.

Also, is /home/yannic/sdc an SSD, or something slower? What filesystem are you using?

**Comment by Yannic** [comment]
`/home/yannic/sdc` is a 6TB HDD.

I've been using 1TB for a while now. What could have happened is that I used to run `v2.x` until ~1 week ago, then ~~upgraded~~ downgraded to `v1.3.3` because I was unter the impression that fixes the go-routine crash I've been seeing about once a week for a while, that used the old FS layout (I saw 10+ hours build time on the first build), and the upgrade to `v2.1.4` migrated all the old data and pushed it over the limit.

Let me compute the size of the cache dir and report back.

**Comment by Yannic** [comment]
```
yannic@debian:~$ du -h -d1 sdc/bazel-remote
6.3G	sdc/bazel-remote/ac.v2
1.1M	sdc/bazel-remote/raw.v2
931G	sdc/bazel-remote/cas.v2
938G	sdc/bazel-remote
```

**Comment by mostynb** [comment]
Perhaps you can try this: https://github.com/buchgr/bazel-remote/pull/480 ?

**Comment by mostynb** [comment]
I think this should be fixed on the tip of the master branch now, but I haven't made a new release yet.

We can reopen this issue if you're still hitting this crash.
