### ISSUE TITLE
How to check for liveness/readiness on Kubernetes

### ISSUE THREAD

**Issue by el-psycho** [buchgr/bazel-remote#48]
Probing http://mybazelremote.local/ returns error 400 causing Kubernetes liveness and readiness checks to fail. What path can we use to probe the server's health? eg. http://mybazelremote.local/healthz

Thanks.

**Comment by nicolov** [comment]
`/status` will return a json with some debug information.

**Comment by HiFaraz** [comment]
@nicolov It would be great to have this in the documentation. Would you welcome a PR to add this info to the README?

**Comment by nicolov** [comment]
Sure
