### ISSUE TITLE
Mac M1/ARM 64 Architecture

### ISSUE THREAD

**Issue by herman-rogers** [buchgr/bazel-remote#484]
Getting this error on a M1 Mac:

"bazel-remote-cache Error"
no matching manifest for linux/arm64/v8 in the manifest list entries

We could use a different image that wraps this one but wanted to see if there was a fix in place before doing so.

**Comment by mostynb** [comment]
Are you accidentally trying to run an amd64 container on your M1 mac? Maybe an arm64 image would work better, eg: https://hub.docker.com/layers/17318545/buchgr/bazel-remote-cache/latest/images/sha256-43299f4b1d39f5a2ce5bbe979e16401662d185479225fa2c611bf2a8afc03099

**Comment by mostynb** [comment]
Closing due to lack of feedback. (I have added linux and mac arm64 binaries to the releases here on github, in case that's useful.)
