### ISSUE TITLE
[Suggestion] There should be a major.minor tag along with the `latest` tag  in the published docker image

### ISSUE THREAD

**Issue by ubatmongo** [buchgr/bazel-remote#494]
The docker image tagged as `latest` should also have a major.minor tag and SHA tag associated with it. 

Recently our deployment failed, as a new required variable was added in run command. To prevent this situation later, we wanted to use a SHA tag from repo digest, but that failed. 

```bash
docker inspect buchgr/bazel-remote-cache:latest | jq -r '.[0].RepoDigests[0]'
```

So had to start using the previous release `v2.2.0`.

**Comment by mostynb** [comment]
Hi, sorry about the breakage.

I think the latest tag should only be used for testing- for production deployments I strongly recommend using a versioned tag (like v2.2.0 as you switched to).

I don't have a great understanding of the docker runtime, and I don't quite understand what you're suggesting. I seem to get a result when I run this:
````
$ docker pull buchgr/bazel-remote-cache:latest
latest: Pulling from buchgr/bazel-remote-cache
e8d8785a314f: Already exists 
a000eabdb57b: Pull complete 
eff4efe25007: Pull complete 
Digest: sha256:5e1aa80cd5e7ef8bdf427e5cdadfbab45e8b3395570c8dae58de21e9588a0672
Status: Downloaded newer image for buchgr/bazel-remote-cache:latest
docker.io/buchgr/bazel-remote-cache:latest
$ docker inspect buchgr/bazel-remote-cache:latest | jq -r '.[0].RepoDigests[0]'
buchgr/bazel-remote-cache@sha256:5e1aa80cd5e7ef8bdf427e5cdadfbab45e8b3395570c8dae58de21e9588a0672
````

However, that hash doesn't seem to match either the amd64 or arm64 hash mentioned on https://hub.docker.com/layers/17318545/buchgr/bazel-remote-cache/latest/images/sha256-1d7d297d3dfb7af71917b544b3600643a24a5f2ba10b935a0e63489e0270d083?context=repo - so I'm not sure what that RepoDigests field in the docker inspect is supposed to show.

**Comment by ubatmongo** [comment]
Hi,
Thanks for the reply! The suggestion is to add multiple tags to the latest version. A `major.minor` version alongside `latest` would have helped.

Thanks for letting me know that `latest` is for debug/test purpose.

**Comment by mostynb** [comment]
So for example, you would like a `2.0` tag that points to the latest `v2.1.x` release?

**Comment by ubatmongo** [comment]
> So for example, you would like a `2.0` tag that points to the latest `v2.1.x` release?

Yes, that helps us to test the latest version and then pin it if it works well.

**Comment by mostynb** [comment]
I created a v2.3.0 release just now, and pushed a "latest-2.3" tag to docker hub. I will try to update this for subsequent v2.3.X releases (if there are any), if it's useful.
