### ISSUE TITLE
Bazel kubernetes CrashLoopBackOff

### ISSUE THREAD

**Issue by rotarur** [buchgr/bazel-remote#495]
Good morning,

I have an issue with my bazel-remote cache container which is in CrashLoopBackOff. after a while of running. I don't have any logs of what's happening neither do I have events about it in my cluster. I tried with emptyDir volume and with persistent volume to check if it's not from the type of disk used, both with the same issue. I tried with the latest version v2.2.0 and with the previous one v2.1.4.

My kuberentes cluster is v1.21.4-eks-033ce7e in AWS.
The backend I'm using is AWS S3.

Please help me to solve this issue. Thanks

**Comment by rotarur** [comment]
i think i found the issue. I've setup the idle timer to 5 min and after that time the pod crashes with an error and enters in CrashLoopBackOff

```
Using S3 backend.
2021/11/08 09:32:09 bazel-remote built with go1.17.1 from git commit a914031a29d96ab40740de4116243b8e63ebc30a.
2021/11/08 09:32:09 Initial RLIMIT_NOFILE cur: 1048576 max: 1048576
2021/11/08 09:32:09 Setting RLIMIT_NOFILE cur: 1048576 max: 1048576
2021/11/08 09:32:09 Loading existing files in /cache.
2021/11/08 09:32:09 Sorting cache files by atime.
2021/11/08 09:32:09 Building LRU index.
2021/11/08 09:32:09 Finished loading disk cache files.
2021/11/08 09:32:09 Loaded 0 existing disk cache items.
2021/11/08 09:32:09 Authentication: basic
2021/11/08 09:32:09 Access mode: authentication required
2021/11/08 09:32:09 Mangling non-empty instance names with AC keys: enabled
2021/11/08 09:32:09 Starting idle timer with value 5m0s
2021/11/08 09:32:09 Starting HTTP server on address :8080
2021/11/08 09:32:09 HTTP AC validation: enabled
2021/11/08 09:32:09 Starting gRPC server on address :9092
2021/11/08 09:32:09 gRPC AC dependency checks: enabled
2021/11/08 09:32:09 experimental gRPC remote asset API: disabled
2021/11/08 09:37:09 Shutting down after idle timeout
2021/11/08 09:37:09 bazel-remote terminated:http: Server closed
```

This issue prevents us to use it the right way because the kubernetes will increase the time between each restarts and the service has no endpoint while it's in crash state and we get an http error 503 until it's recovered.

Please can you check this issue ASAP?

**Comment by rotarur** [comment]
the idle timeout should not crash the server, only the connections if there are such 🙏

**Comment by mostynb** [comment]
Hi, the `--idle_timeout` flag sounds like it's working as intended here- it makes bazel-remote exit after not having any incoming requests for a certain time. Can you run bazel-remote without that flag?

**Comment by rotarur** [comment]
will try without the flag. Now i'm using curl command to keep the server alive and in 58m no crashes happened. but this is not an ideal solution, it's very ugly

**Comment by mostynb** [comment]
Some users run bazel-remote on the client side, and want it to exit if it's idle for a certain amount of time. This feature is off by default because it's not a common use case. It sounds like you want the default behaviour here (ie don't specify this flag).

I don't want to rename the flag because that would break backwards compatibility, but we could improve the help text if you have suggestions. Here's the current text:
````
   --idle_timeout value The maximum period of having received no request
      after which the server will shut itself down. (default: 0s, ie disabled)
      [$BAZEL_REMOTE_IDLE_TIMEOUT]
````

**Comment by rotarur** [comment]
true, maybe it's better to improve the docs. thanks for explanation

**Comment by mostynb** [comment]
OK- marking this issue closed since this is working as intended. If you have suggestions for improving the help text for this option, feel free to open a PR.
