### ISSUE TITLE
Prefix Action Cache and CAS

### ISSUE THREAD

**Issue by BenTheElder** [buchgr/bazel-remote#5]
It seems like the AC and CAS hashes could collide since they both appear to be stored in `<cache>/<hash>`.

Perhaps instead we could store them at `<cache>/ac-<hash>` and `<cache>/cas-<hash>`?

**Comment by buchgr** [comment]
Hi Ben,

that's a great idea. I think we should do this so it makes debugging easier (understand what's a metadata entry and what's a blob). I am not worried about collisions, as the whole idea of content-addressable storage assumes that there are none. The whole system would break down :).

**Comment by BenTheElder** [comment]
Are the action cache and CAS not distinct?

>The remote cache stores two types of data:
>
> • The action cache, which is a map of action hashes to action result metadata.
> • A content-addressable store (CAS) of output files.

Per https://docs.bazel.build/versions/master/remote-caching.html#remote-caching-overview

**Comment by buchgr** [comment]
That's correct! However, it doesn't change anything about what I wrote above. The CAS files are named after `SHA256(file content)` and the action cache files are named after `SHA256(action)`. So unless we can get hash collisions (and the assumption is we can't) - we are fine.

**Comment by nicolov** [comment]
I created a PR for this https://github.com/buchgr/bazel-remote/pull/8

**Comment by nicolov** [comment]
Also, just to clarify things: the Action Cache is _not_ content-addressable. The file name is `hash(Action)`, and the content is its corresponding `ActionResult`.

This means that the current configuration could be a problem in the (very unlikely) case that a serialized Action is _also_ an input/output of the build process. In this case, the AC would store the `ActionResult` under the same filename as the CAS would store the serialized `Action` itself. However, I can't really think why this would happen in practice.

**Comment by BenTheElder** [comment]
Right, this seems *very* unlikely but I also don't see any guarantees around the inputs / format for the bytes used in the action hash. 


FWIW I've been toying with a slightly different implementation for other reasons (mostly supporting arbitrarily many caches in one server) and separating these has indeed been useful for debugging.

**Comment by buchgr** [comment]
You are both right - I am wrong :-). Either way @nicolov just sent a fix! Yay!

**Comment by buchgr** [comment]
fixed by #8
