### ISSUE TITLE
Publish images to public.ecr.aws / quay.io

### ISSUE THREAD

**Issue by jrroman** [buchgr/bazel-remote#509]
Could we publish images to public quay.io and or public.ecr.aws repositories? 

This would benefit the majority if we ever run into DockerHub outages like what occurred on 12/20/21 or when users run into rate limiting issues due to DockerHub's limitations.

I would be willing to open the PR but i need the repositories created before I create the bazel build rules.

**Comment by mostynb** [comment]
I can publish images to other free registries if it would be helpful. What's the best alternative registry?

**Comment by jrroman** [comment]
That would be great, `public.ecr.aws` or `quay.io` can both be published to for free.

**Comment by mostynb** [comment]
Could you try `quay.io/bazel-remote/bazel-remote:latest` ? If that works I'll try to go back and push some release tags there too.

**Comment by mostynb** [comment]
I think the quay.io setup should be working now, I have copied all the previous tags there. Please reopen this issue if you spot any problems.

**Comment by ldx** [comment]
@mostynb I tried the image from quay.io and works via `docker run`. Thank you both.

**Comment by jrroman** [comment]
@mostynb i was able to test it this afternoon locally with a docker pull and run. Thank you for doing this, much appreciated!

@ldx thank you for testing as well
