### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by arobinson** [buchgr/bazel-remote#547]
I'm following the instructions on the readme, and docker fails to run:
```
2022/04/29 18:08:01 bazel-remote built with go1.18 from git commit 6078764573e5a22ecc9aadb100c484a0ff88086f.
2022/04/29 18:08:01 Initial RLIMIT_NOFILE cur: 32768 max: 65536
2022/04/29 18:08:01 Setting RLIMIT_NOFILE cur: 65536 max: 65536
2022/04/29 18:08:01 mkdir /data/cas.v2: permission denied
```
I've tried running it as both my user and sudo and tried different paths. I tried this first:
```
docker run -u 1000:1000 -v /home/myuser/bazel_cache:/data -p 9090:8080 -p 9092:9092 buchgr/bazel-remote-cache
```

I got the same issue with:
```
sudo docker run -u 1000:1000 -v /cache:/data -p 9090:8080 -p 9092:9092 buchgr/bazel-remote-cache
```

I got the same error message from trying to use the quay.io instructions.

Note that I'm trying to run this on an AWS workspace (RPM based distro)

Perhaps some steps are missing for setting it up?

**Comment by mostynb** [comment]
Hi, does `/home/myuser/bazel_cache` exist (or `/cache` from your sudo example) ? If so, what are their permissions? Could you run `ls -ld /home/myuser/bazel_cache` (and similarly for `/cache`) and share the results here?

**Comment by mostynb** [comment]
Oh, and another thing to check is if your (non-root) user/group id are 1000. If not, you should change the `-u 1000:1000` argument to match your actual uid and gid. You can check with the `id` command.

**Comment by mostynb** [comment]
Hi, did you figure out what the problem was?

**Comment by arobinson** [comment]
No sorry, I gave up and used a different tool instead (direct webdav)

**Comment by mostynb** [comment]
No problem.

Closing this since I have no way to debug it myself (but I assume it was a simple ownership/permission error).

**Comment by Wentaobi** [comment]
`sudo docker run -u 1000:1000 -v ~/Desktop/ws/dummy_remote_cache:/data -p 9090:8080 -p 9092:9092 quay.io/bazel-remote/bazel-remote
`
2023/01/17 08:47:49 bazel-remote built with go1.19.4 from git commit be88dadd8d6e94f4634def7e1b97290acea3a7f0.
2023/01/17 08:47:49 Initial RLIMIT_NOFILE cur: 1048576 max: 1048576
2023/01/17 08:47:49 Setting RLIMIT_NOFILE cur: 1048576 max: 1048576
2023/01/17 08:47:49 Storage mode: zstd
2023/01/17 08:47:49 Zstandard implementation: go
2023/01/17 08:47:49 Limiting concurrent file removals to 5000
2023/01/17 08:47:49 mkdir /data/cas.v2: permission denied

I had similar issues above, here is how I solved:
`chmod 777  ~/Desktop/ws/dummy_remote_cache
`
I know it's not good, I can drop +x later on. FYI.
