### ISSUE TITLE
What max_size means when S3 backend used

### ISSUE THREAD

**Issue by al-babych-fivetran** [buchgr/bazel-remote#549]
Sorry for this question, but I can't find an answer in the readme and previous issues.

I have a configuration with max_size=10 and S3 backend.

Is it mean that bazel-remote will use 10G of local disk space and unlimited size of S3?
Or both S3 and the local disk will be limited to 10G.

I don't think config matters, but:

```
docker run -u 1000:1000 -v /home/ec2-user/cache:/data -v /home/ec2-user/.aws:/aws-config \
   -v /home/ec2-user/.htpasswd:/etc/bazel-remote/htpasswd \
   -p 9090:8080 -p 9092:9092 buchgr/bazel-remote-cache \
   --s3.auth_method=aws_credentials_file --s3.aws_profile=default \
   --s3.aws_shared_credentials_file=/aws-config/credentials \
   --s3.bucket=bazel-remote-cache1 --s3.endpoint=s3.us-east-1.amazonaws.com \
   --htpasswd_file /etc/bazel-remote/htpasswd \
   --max_size=10 
```

**Comment by mostynb** [comment]
Hi, the `max_size` setting only applies to bazel-remote's local disk cache. There is no automatic size management for the optional proxy backends (like s3) unless you can arrange that in the backend services themselves.

**Comment by mostynb** [comment]
Updated the help text to point out that the max_size only applies to the disk cache.
