### ISSUE TITLE
Add a s3 as a supported backend

### ISSUE THREAD

**Issue by bshashank** [buchgr/bazel-remote#56]
I like the bazel-remote project, but storing the files on disk may not scale for our needs.

Some of the remote execution implementations (such as build-grid and build-barn) also allow storing the cache objects in S3.

I'd be nice for bazel-remote to have the same capability.

**Comment by mostynb** [comment]
A rebased version of #57 landed recently: https://github.com/buchgr/bazel-remote/pull/80
