### ISSUE TITLE
Сommand line options and endpoint_metrics_duration_buckets

### ISSUE THREAD

**Issue by BobIsOnFire** [buchgr/bazel-remote#567]
Hi!

I am currently using command line options to configure things like cache storage size dynamically. I also monitor endpoint metrics, and now I would like to override default duration buckets because they hardly give me any useful information (my cache server is used in a local network and almost all requests take much less than 0.5s). Unfortunately, `endpoint_metrics_duration_buckets` could only be set in YAML file, using which AFAIU ignores any config that I have set in the command line.

**Question**: Is there a way to _both_ configure duration buckets and set some other options dynamically?

If not, do you consider making `endpoint_metrics_duration_buckets` config available in command line / environment? [Feature commit](https://github.com/buchgr/bazel-remote/commit/6b64010b870602712c6ec6ddf8a349427fcf4c67) mentions that it is not a good idea, but I am confused as to why other options are available and this one is not.

**Comment by mostynb** [comment]
The reasoning behind only supporting this option via config file is that it feels like it would be complicated to specify on the command line, and at some point we suspect advanced users would prefer to use a config file anyway. All the other options that can be set from the command line are simple in comparison.

Just curious: how are you dynamically adjusting the max_size setting?

**Comment by mostynb** [comment]
Closing for now due to lack of feedback.
