### ISSUE TITLE
Filesystem storage with proxy backend

### ISSUE THREAD

**Issue by shubhindia** [buchgr/bazel-remote#572]
This is not really an issue but a question. When we enable proxy backend, local filesystem will be used or not? Don't want to go through the code to find answer for such simple question.
PS - Is there a slack channel or a community page where such questions can be posted and people can answer those?

**Comment by ulrfa** [comment]
Please see: https://bazel.build/help.md

**Comment by shubhindia** [comment]
> Please see: https://bazel.build/help.md

My question was specific to `bazel-build` . I couldn't find the answer to my question on bazel forum as well. Hence, posted here.

**Comment by mostynb** [comment]
I'm not sure if you're asking about bazel-remote or about bazel...

bazel-remote uses a local disk cache, with an additional optional proxy backend- it always needs at least some disk cache (though it needs less if you use one of the proxy backends).

Bazel has its own disk cache, but I'm not sure how that works. You could try asking about Bazel on https://bazelbuild.slack.com/ or https://groups.google.com/g/bazel-discuss

**Comment by shubhindia** [comment]
> (though it needs less if you use one of the proxy backends)

So this means all/some of the cache will be stored in the remote and not where `bazel-remote` is running?
Right now we use a `local server` as `bazel-remote` to which only our CI machines have access. Now, it we are to give access to all the developers, we will have to give them access to this `local server`. Solution for this could be replicate this cache to `GCS` or any bucket preferred and give developers access to this `GCS bucket` and not to the `local server`. Hence, my question, when we enable `proxy backend`, is the cache replicated to the enabled backend or all the cache will be stored to the backend and the machine where `bazel-remote` is actually running will just redirect the request?

**Comment by mostynb** [comment]
> So this means all/some of the cache will be stored in the remote and not where bazel-remote is running?
Right now we use a local server as bazel-remote to which only our CI machines have access. Now, it we are to give access to all the developers, we will have to give them access to this local server. Solution for this could be replicate this cache to GCS or any bucket preferred and give developers access to this GCS bucket and not to the local server. Hence, my question, when we enable proxy backend, is the cache replicated to the enabled backend or all the cache will be stored to the backend and the machine where bazel-remote is actually running will just redirect the request?

When using bazel-remote with a proxy-backend, for cache lookups:

**Comment by shubhindia** [comment]
Cool, that means it is a replication of some kind.

**Comment by mostynb** [comment]
Sounds like you have the answer you're looking for now?

BTW, I created a #bazel-remote channel in buildteamworld.slack.com, but I'm the only one in there, and I'm not sure how closely I can watch it.

**Comment by sanju-naik** [comment]
@mostynb 
> 2. Otherwise try to return a value from the proxy backend, and store that in the disk cache

Is there a way to stop this? Say if the Cache URL is `http://machine-ip-address` look up only in the local disk cache, if not found stop it there. But write/upload should happen to both local disk as well as proxy backend. 

Similarly, when the cache URL is `gcs-buket-url` just look up only in the GCS bucket, We would directly use GCS bucket URL only from developer machines and we will only read from the cache here. 

The above flexibility would help us to avoid unnecessary lookups, i.e when something is not found in local disk cache most likely it won't be available in GCS bucket too, say when we set up the same LRU cleaning strategy on both. Also for our CI workers, we want to avoid GCS look-up as that happens over the Internet and can be slow to download from cache.

**Comment by mostynb** [comment]
I don't think bazel-remote currently has a way to do what you're asking for, but I probably misunderstand your setup. Would it make sense for you to run two caches, one with only disk cache and one with disk cache + cloud storage backend? Then your clients could use whichever cache server has the behaviour they want.

**Comment by shubhindia** [comment]
> Is there a way to stop this? Say if the Cache URL is `http://machine-ip-address` look up only in the local disk cache, if not found stop it there. But write/upload should happen to both local disk as well as proxy backend.
> 
There is no flag or something which we can pass, but this can be stopped (We will have to run a forked version for this)
> Similarly, when the cache URL is `gcs-buket-url` just look up only in the GCS bucket, We would directly use GCS bucket URL only from developer machines and we will only read from the cache here.
> 
Yes, if the cache URL is gcs bucket, then the `bazel-remote` will never come in picture.

**Comment by shubhindia** [comment]
> Cool, that means it is a replication of some kind.

@mostynb So, I was going through code and found https://github.com/buchgr/bazel-remote/blob/master/cache/disk/disk.go#L715 , CMIIW but this means this is replication but for newer blobs only?? Like whenever a blob is uploaded to `bazel-remote` is will be stored in both `local-disk` and `proxy` (asynchronously) but the blobs which were there before enabling the `proxy-backend` will remain in `local-disk` only?
I even checked our cache and its around `325GB` in `local disk` and `2.56GB` in `GCS bucket`

**Comment by mostynb** [comment]
> @mostynb So, I was going through code and found https://github.com/buchgr/bazel-remote/blob/master/cache/disk/disk.go#L715 , CMIIW but this means this is replication but for newer blobs only?? Like whenever a blob is uploaded to `bazel-remote` is will be stored in both `local-disk` and `proxy` (asynchronously) but the blobs which were there before enabling the `proxy-backend` will remain in `local-disk` only?

That is correct.

If you wanted to trigger a resync, you could experiment with a script that gets a directory listing of bazel-remote's cache dir, extracts the AC and CAS blob hashes, and downloads + uploads each of them using http://127.0.0.1/ URLs (but you'd want to try throttling it because the proxy backends upload asynchronously and they drop upload requests if there are too many waiting requests).

Is this a reasonable summary of your desired setup?
* CI runners use a local bazel-remote instance with reasonably large cache. You want these to read and write from bazel-remote's disk cache, and for bazel-remote to asynchronously upload to a GCS backend, but you do not want CI runners to get cache hits from the GCS backend.
* Developers use the GCS bucket for remote cache directly (either read/write or readonly). Cache entries are never synced from GCS to the bazel-remote instance.

**Comment by mostynb** [comment]
IIRC if you use `--storage_mode uncompressed` then the blobs will be stored uncompressed in both bazel-remote's disk cache and in the proxy backend.

**Comment by shubhindia** [comment]
@mostynb bazel supports zstd compression. It's just by default bazel uses `cas` and not `cas.v2` directory (same for other directories as well). So when we in case of GCS bucket when we bypass `bazel-remote` bazel doesn't pull anything because the directories in GCS are `*.v2` and not the ones which bazel looks for. Any particular reason why we are using suffix `.v2` in `bazel-remote` ?

**Comment by mostynb** [comment]
The file format of bazel-remote blobs is considered an internal detail to bazel-remote. When using `--storage_mode zstd` the CAS blobs are stored in compressed form, with their uncompressed sha256 hash in the filename in the disk cache, and the proxy backends include "cas.v2" in the key (for cas blobs only), to distinguish them from CAS blobs stored in uncompressed form.

IIUC when you configure bazel to use GCS as remote cache directly then you need to use http instead of the REAPI gRPC protocol, and bazel then probably assumes that these blobs are stored uncompressed. So if bazel were to download a compressed blob from GCS, it would fail the sha256 check and be rejected.

On the other hand, if you use bazel-remote with `--storage_mode uncompressed`, then it will store uncompressed CAS blobs in the disk cache, and also uncompresed on the proxy backends without "cas.v2" in the path name. And bazel should be able to download and understand these when using GCS directly.

**Comment by shubhindia** [comment]
> IIUC when you configure bazel to use GCS as remote cache directly then you need to use http instead of the REAPI gRPC protocol, and bazel then probably assumes that these blobs are stored uncompressed. So if bazel were to download a compressed blob from GCS, it would fail the sha256 check and be rejected.
> 
We are using http only. 
> On the other hand, if you use bazel-remote with `--storage_mode uncompressed`, then it will store uncompressed CAS blobs in the disk cache, and also uncompresed on the proxy backends without "cas.v2" in the path name. And bazel should be able to download and understand these when using GCS directly.
>
I tried using `--storage-mode uncompressed` but it didn't make any difference. It still created directories with `.v2` suffix.

**Comment by mostynb** [comment]
> I tried using `--storage-mode uncompressed` but it didn't make any difference. It still created directories with .v2 suffix.

The disk cache always uses directories with the .v2 suffix, but in uncompressed storage mode the proxy backends are supposed to upload CAS blobs without .v2 in the path. The gcsproxy package is a wrapper for httpproxy and here's where it does that:
https://github.com/buchgr/bazel-remote/blob/1975376ebb07c02af4f787a3380fcca4f4799d93/cache/httpproxy/httpproxy.go#L127

**Comment by shubhindia** [comment]
Tested with the above flag and it is working fine. Was able to use the cache from GCS as expected. Thanks @mostynb . Maybe I'll add a flag to disable additional lookup when the cache is not found locally but for now I guess we can close this.
