### ISSUE TITLE
Support for AWS IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by priestjim** [buchgr/bazel-remote#578]
We recently tried to migrate our `bazel-remote` instance from using `kube2iam` annotations to start using "best practice" AWS IRSA architecture, as a way to access our S3 cache bucket. 

This process involves removing the `kube2iam` annotation from the `bazel-remote` pod, adding a service account with an AWS role ARN annotation and setting that service account in the `bazel-remote` deployment. 

Upon integration of this architecture, the following env vars become available to the instance: `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_REGION`. Standard AWS SDK version picks this configuration automatically to assume the correct role and access AWS resources.

After integrating the above changes to `bazel-remote`, it seems like it does not assume the correct role and uploads to S3 fail silently with `EOF` rather than `OK`. The role to be assumed bears the exact same resource policy as the legacy `kube2iam` role and both roles' access is registered in the S3 bucket.

Please advise.

**Comment by mostynb** [comment]
Since bazel-remote uses the minio-go client instead of the standard aws client, we might need to add some extra plumbing for this to work. Unfortunately, I don't have an AWS account to use for testing this directly- but maybe the minio server supports the same feature?

**Comment by priestjim** [comment]
In retrospect, `bazel-remote` supports the IRSA setup correctly. But if the IAM endpoint is overridden in `bazel-remote`'s configuration with the local metadata endpoint (which we were doing), it overrides the default `sts.amazonaws.com` and as such fails to authenticate. The solution to this is to simply remove the `iam_role_endpoint` when using IRSA infrastructure.
