### ISSUE TITLE
panic when nil pointer dereference

### ISSUE THREAD

**Issue by csh2022** [buchgr/bazel-remote#602]
![nil_pointer](https://user-images.githubusercontent.com/24428215/201807725-715b5f18-8761-4e34-ac42-7e7aa8e3c1b4.png)
there is a panic when s.cache.Get returned nil ReadCloser pointer, so some protection was needed.
https://github.com/buchgr/bazel-remote/blob/master/server/grpc_cas.go#L143
![image](https://user-images.githubusercontent.com/24428215/201808101-efa0e03c-932e-4b62-afc4-fbb60bcbc13f.png)
maybe like this or add some recover logic, please fix it, thanks.
![image](https://user-images.githubusercontent.com/24428215/201808293-64a049cb-fcbb-4725-a563-b31f8fbc2e44.png)

**Comment by csh2022** [comment]
https://github.com/buchgr/bazel-remote/blob/master/server/grpc_cas.go#L143

**Comment by mostynb** [comment]
Thanks for reporting this, your suggested patch looks good: https://github.com/buchgr/bazel-remote/pull/603

I will land this once CI finishes, but I won't be able to update the dockerhub/quay.io container images until tomorrow.
