### ISSUE TITLE
Can I store files with arbitrary checksum generation?

### ISSUE THREAD

**Issue by Cluster7ck** [buchgr/bazel-remote#604]
First of all: I was planning on using this server for storing build artifacts which are not generated by bazel so this might just be out of scope.

I am generating the sha256 from the files that are used to generate the resulting binary. Then when I do a PUT with `/cas/my-generated-id` i get:
```
checksums don't match. Expected ab4c0ae56fa464863c133ec2d4607fbc36dfbe869909713c392e4dd874693c91, found 11e0900e166a593f26fa999a73b1ea9174bea4b29f4cf15cd8e1ac4e0c323045
```

I looked into the code and sure enough the sha256 for the uploaded file is generated and compared to the provided sha.
My question comes from (probably) misunderstanding how bazel works:

Doesn't bazel _also_ generate the sha256 _before_ building the artifact from files/env variables/parameters? Isn't that the whole trick? Where does the assumption come from that the sha256 should be that of the file? Maybe you can clear up my confusion.

**Comment by Cluster7ck** [comment]
Nvm read the docs.

> Bazel breaks a build into discrete steps, which are called actions. Each action has inputs, output names, a command line, and environment variables. Required inputs and expected outputs are declared explicitly for each action. You can set up a server to be a remote cache for build outputs, which are these action outputs. These outputs consist of a list of output file names and the hashes of their contents. With a remote cache, you can reuse build outputs from another user's build rather than building each new output locally.

I understand this as: I need to create those actions and the corresponding meta data and then upload the files with their sha256

**Comment by mostynb** [comment]
If you want to use bazel-remote as a memcached-style LRU (but with a filesystem backing store), ie without sha256 verification, you can use the `--disable_http_ac_validation` flag, and use URLs of the format /ac/<hex string the same length as sha256 hashes>
