### ISSUE TITLE
context deadline exceeded when doing PUT of http://169.254.169.254/latest/api/token 

### ISSUE THREAD

**Issue by diegohavenstein** [buchgr/bazel-remote#608]
I am trying to use the docker image to run a remote bazel cache.

This is how I am running the container:
```
docker run -v /data:/data -p 9090:8080 buchgr/bazel-remote-cache --s3.endpoint=s3.amazonaws.com --s3.bucket=<name-of-my-bucket>  --s3.auth_method=iam_role --s3.region=us-west-2 --max_size=500
```

Then I run a Bazel build which uploads local results. It results in these errors:

```
2022/11/22 13:48:16 S3 DOWNLOAD <name-of-my-bucket> ac/df/df8d0ea898bc2d2efc6e6efbeef290454e5b3318d92bdec7faa9b25dc8e414e7 Put "http://169.254.169.254/latest/api/token": context deadline exceeded
```

I can get valid credentials from 169.254.169.254 on the machine the docker container is running. Due to these errors probably I'm not seeing any entries created in the bucket

Hope you can help me out, thx!

**Comment by mostynb** [comment]
Hi, unfortunately I don't have an AWS account to test this sort of thing myself.

Do you get this error immediately when bazel starts making cache requests? Have you tried increasing bazel's remote execution/cache timeout: https://bazel.build/reference/command-line-reference#flag--remote_timeout ?

BTW, I notice that you have set a 500G (local) cache size limit, beware that this does not set a limit on the size of artifacts stored on s3.

**Comment by diegohavenstein** [comment]
I guess one issue is that it seems to try to PUT to http://169.254.169.254/latest/api/token. This is not available on the EC2 instances we run

**Comment by diegohavenstein** [comment]
Found the problem. I started the docker container, and did not use `--network=host`. If this is not done, 169.254.169.254 is not reachable from inside the container.

So maybe just updating the documentation is enough, i.e. mentioning that `--s3.auth_method=iam_role` will only work if `--network=host` is set

**Comment by mostynb** [comment]
Thanks- how does https://github.com/buchgr/bazel-remote/pull/630 look?

**Comment by diegohavenstein** [comment]
looks great, thx!

**Comment by diegohavenstein** [comment]
Closing issue

**Comment by mostynb** [comment]
Thanks again.
