### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Bazel Remote Cache in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [buchgr/bazel-remote#609]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazel Remote Cache. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-46a5-40ec-bf34-cd6f88f0c0d3)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-46a0-47b9-b802-ace9e5ce953b)
- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-46a3-4662-a658-c147a99d15bb)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by mostynb** [comment]
This was difficult to find in the logs, but I think the error is in rules_go:
```
(01:15:11) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/01fdca1b9dd1e1722bed67715b665b3f/external/io_bazel_rules_go/BUILD.bazel:106:10: in go_config rule @io_bazel_rules_go//:go_config: target '@io_bazel_rules_go//go/private:stamp' is not visible from target '@io_bazel_rules_go//:go_config'. Check the visibility declaration of the former target if you think the dependency is legitimate
(01:15:11) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/01fdca1b9dd1e1722bed67715b665b3f/external/io_bazel_rules_go/BUILD.bazel:106:10: Analysis of target '@io_bazel_rules_go//:go_config' failed
(01:15:11) ERROR: Analysis of target '//utils/idle:go_default_test' failed; build aborted:
```

#610 upgrades rules_go, in an attempt to fix this.
