### ISSUE TITLE
Pushing latest to DockerHub?

### ISSUE THREAD

**Issue by mpassell** [buchgr/bazel-remote#62]
I'm able to pull down the latest code, build it, and run it (admittedly without exhaustive testing), but was curious if anyone would be pushing the latest to DockerHub in the near future.

**Comment by mpassell** [comment]
Can you build yourself and try it out? [Bazel's not too much of a pain to install](https://docs.bazel.build/versions/master/install.html) and the bazel-remote build pulls down it's own copy of go. If it does fix your problem, that could be an extra motivation for the project maintainer(s) to push the latest to DockerHub...

**Comment by mostynb** [comment]
(spring cleaning) docker hub should be updated more frequently now.
