### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Bazel Remote Cache in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [buchgr/bazel-remote#620]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazel Remote Cache. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c1f4-4d77-8bac-0875aa51b55b)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c1ea-4594-bd19-2bfa0f7c5812)
- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c1ef-4dc0-887c-8c842aa55a05)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by mostynb** [comment]
I guess this requires a rules_docker update:

**Comment by mostynb** [comment]
Filed bazelbuild/rules_docker#2196 to try to fix this upstream.
