### ISSUE TITLE
[Azure Blob Storage] Not removing actual blobs from storage

### ISSUE THREAD

**Issue by fineconstant** [buchgr/bazel-remote#626]
We use bazel-remote with Azure Blob Storage as a backend.
According to `/status` endpoint, bazel-remote `CurrSize` reached ~99% of `MaxSize` so bazel-remote is keeping cache size not exceeding that set by `--max_size` flag.

```
{
  "CurrSize": 1066475520,
  "UncompressedSize": 1192097287,
  "ReservedSize": 0,
  "MaxSize": 1073741824,
  "NumFiles": 21530,
  "ServerTime": 1673264602,
  "GitCommit": "b899a9d0f9d086a25e9ec51ccba8dafbc36ca8eb",
  "NumGoroutines": 690
}
```
However, when we checked the actual size of Blob Container used by Bazel it is over 42,18 GiB (45 294 542 251 bytes) now.
I looks like as bazel-remote is keeping track of certain numbers of blobs but actually not removing them from storage.

**Comment by mostynb** [comment]
That is correct- bazel-remote does not attempt to keep track of the storage space used on the proxy backends. The s3 backend has an option to update the timestamps of blobs as they are accessed, which could potentially be used with some sort of s3-side retention policy.

I don't have an azure account to test the azblob backend with, but I would accept patches that attempt to solve this problem.

**Comment by fineconstant** [comment]
Thank you for clarifying that 👍🏻  So just additional question, does setting `--max_size` currently make sense when using proxy backeds?

**Comment by mostynb** [comment]
bazel-remote always uses a disk cache (even when using a proxy backend), and the `--max_size` value refers only to the size of the disk cache. When downloading a blob from a proxy backend, it's written into the local disk cache before being sent to the client.
