### ISSUE TITLE
Implement support for the gRPC-based caching protocol

### ISSUE THREAD

**Issue by buchgr** [buchgr/bazel-remote#64]
https://github.com/bazelbuild/remote-apis

**Comment by nicolov** [comment]
I have code for this I can push (was prototyping a remote execution server).

**Comment by buchgr** [comment]
that would be lovely :-)

**Comment by scele** [comment]
@nicolov could you push your changes? I'd love to try this out! :)

**Comment by nicolov** [comment]
I started updating my code to use the new `v2` grpc definitions when I saw your message, but I realized that https://github.com/EdSchouten/bazel-buildbarn has a storage-only grpc endpoint, and it seems well done.

**Comment by mostynb** [comment]
I have made a start on this. Can anyone recommend a test client that doesn't require an implementation of the Execution service?

**Comment by mostynb** [comment]
We have support for gRPC now (experimental, at least). Closing.
