### ISSUE TITLE
Ignore .DS_Store (and perahps other dot files)

### ISSUE THREAD

**Issue by ericrafalovsky** [buchgr/bazel-remote#640]
## Current behavior
Upon encountering unexpected files, `bazel-remote` fails to start. 

For example,
```
mkdir /home/vagrant/.cache/bazel-remote
touch /home/vagrant/.cache/bazel-remote/.DS_Store
./bazel-remote --dir=/home/vagrant/.cache/bazel-remote --max_size=20 
```

```
2023/02/15 21:32:37 bazel-remote built with go1.19.4 from git commit b899a9d0f9d086a25e9ec51ccba8dafbc36ca8eb.
2023/02/15 21:32:37 Initial RLIMIT_NOFILE cur: 2560 max: 2560
2023/02/15 21:32:37 Setting RLIMIT_NOFILE cur: 2560 max: 2560
2023/02/15 21:32:37 Storage mode: zstd
2023/02/15 21:32:37 Zstandard implementation: go
2023/02/15 21:32:37 Limiting concurrent file removals to 5000
2023/02/15 21:32:37 Loading existing files in /home/vagrant/.cache/bazel-remote.
2023/02/15 21:32:37 Scanning cache directory with 16 goroutines
2023/02/15 21:32:37 Failed to scan cache dir: Unexpected file: .DS_Store
2023/02/15 21:32:37 Loading of existing cache entries failed due to error: Unexpected file: .DS_Store
```

## Feature request
`bazel-remote` should ignore `.DS_Store` files (as well as perhaps some other common types of dot files). When running `bazel-remote` on MacOS, which admittedly is perhaps uncommon, such files can be commonly encountered and this issue can be unnecessary disruptive in causing `bazel-remote` to fail to start up. 

Thanks for all your work on this awesome project ❤️ !

**Comment by mostynb** [comment]
Sounds like a reasonable feature request- landed a change which I think should work.

> Thanks for all your work on this awesome project heart !

Thanks for the kind words- I appreciate it.
