### ISSUE TITLE
Question: local v. remote builds

### ISSUE THREAD

**Issue by gshanemiller** [buchgr/bazel-remote#661]
There are two broad use-cases for builds:

- *local* when developers want to see if their code changes build + test it prior to making a GIT PR
- *strictly remote builds* when PRs are validated prior to approval and merge

According to [build buddy](https://www.buildbuddy.io/blog/bazels-remote-caching-and-remote-execution-explained/#remote-execution) the native Bazel `remote-cache` option among other things:

* Determine if any inputs to the action need to be uploaded
* Then execute the action remotely
* If the action completes successfully, download the action's outputs from the CAS 

So any missing inputs (headers, .c, .cpp etc) are rcp'd to the build farm. This is important because for local builds:

* Developers clone normally on their local machine where edits occur for local work, but outputs are cached
* *IF* those outputs can be reused by PR validation, they are already cached

So what does bazel-remote do beyond this? I gather bazel-remote implement's Bazel's remote execution like: 

* [Buildbarn](https://github.com/buildbarn)
* [Buildfarm](https://github.com/bazelbuild/bazel-buildfarm)
* [BuildGrid](https://gitlab.com/BuildGrid/buildgrid)
* [Scoot](https://github.com/twitter/scoot)

as referenced [here](https://bazel.build/community/remote-execution-services). bazel-remote also reference by Google on a different [page](https://bazel.build/remote/caching#run-bazel-using-the-remote-cache).

In particular, what's the thinking process to do builds (before CI validation) prior to PR submission vs. build PR candidates? Building PR candidates is usually mediated through Jenkins etc., but for this question the key point is they always run on a build-farm. 

Finally, how does bazel-remote scale to multiple boxes? For 10 available remote build boxes, should I run one copy of bazel-remote per macine and, when building jobs, consistently choose one of the 10 boxes for a given job?

**Comment by gshanemiller** [comment]
withdrawing until I better understand remote execution with or without remote-caching. My questions mixes both I think in a confusing way

**Comment by mostynb** [comment]
A short summary of remote caching and remote execution:

Remote caching can be used without remote execution. In this setup clients read build results from and write then to the cache directly as needed. This can improve the best-case build times (assuming that the cache overhead is low enough, and the cache hit rate is high enough).

Remote execution requires a remote cache. In this setup, clients download cached build results if available, and if not upload actions (basically a description of a command to run) as well as all the inputs to the command, and then ask the remote execution service to run the action and populate the remote cache with the results. This can improve the worst-case build times (assuming that the actions are faster to upload to the cache, be run by the remote execution service, and downloaded when compared to waiting for a local CPU core to be available).

Bazel-remote only implements remote caching (but it can be used as the cache server with other remote execution implementations). It mostly scales with network and filesystem throughput/latency. It should be able to handle 10s of clients fairly easily, with suitable network and SSD-like storage (though it depends entirely on the kind of actions you want to cache). When experimenting, I think you should start with a single cache and see how far it scales before you need more advanced setups.
