### ISSUE TITLE
S3 IAM_ROLE <Error> but have <ErrorResponse>

### ISSUE THREAD

**Issue by bu3** [buchgr/bazel-remote#667]
Hi,

I've deployed bazel-remote v2.4.1 on top of an S3 bucket in my k8s cluster.
As long as I used `aws_credentials_file` as `auth_method` it worked like a charm.
Since my company has decided to avoid consuming credentials from file and I switched `auth_method` to `iam_role` instead and now I see my bazel-remote instance reporting many of the messages below:
```
S3 UPLOAD <bucket_name_reducted> cas.v2/3f/<hash_reducted> expected element type <Error> but have <ErrorResponse>
```
```
S3 DOWNLOAD <bucket_name_reducted> ac/90/<hash_reducted> expected element type <Error> but have <ErrorResponse>
```

These are the ENVs I use to configure my bazel-remote instance:
```
BAZEL_REMOTE_S3_BUCKET: '<reducted>'
BAZEL_REMOTE_S3_ENDPOINT: '<reducted>'
BAZEL_REMOTE_S3_AUTH_METHOD: 'iam_role'
```

What am I doing wrong?

Thanks

**Comment by bu3** [comment]
Never mind. It was my fault

**Comment by mostynb** [comment]
If you have suggestions for how to improve the documentation and/or error messages, they're welcome. I don't have a good way to test AWS S3.
