### ISSUE TITLE
Bytestream Write Failures due to Context Cancel

### ISSUE THREAD

**Issue by yav124** [buchgr/bazel-remote#677]
Hey all,

I've been setting up a remote cache instance and seem to be getting bytestream write failures with the only error being `Context Canceled`. I also seem to be getting this error which I guess means the cache is failing while parsing the writes:
```
GRPC BYTESTREAM WRITE FAILED: unknown-resource rpc error: code = Internal desc = rpc error: code = Canceled desc = context canceled
```
All other cache functionality seems to be working fine. I'm using this cache for large `pants` builds/tests.

This leads me to believe that there's a timeout happening on these large write streams. I don't see any options for extending the context timeout. Are there any suggestions of how to approach this issue?

Thanks

**Comment by mostynb** [comment]
I think this might be the client side canceling the request, and if so it's something that you would need to configure on the client side.

I have never used pants myself, but maybe you could try increasing this setting to see if this resolves the issue:
https://www.pantsbuild.org/docs/reference-global#remote_store_rpc_timeout_millis

**Comment by yav124** [comment]
It seemed to be a memory resource issue, ended up using a machine with enough RAM to support my remote cache size fixed this.
