### ISSUE TITLE
File not closed, will it cause resource leakage?

### ISSUE THREAD

**Issue by csh2022** [buchgr/bazel-remote#681]
https://github.com/buchgr/bazel-remote/blob/46ab6a35b660fbfc8869970d805f81eaebec8e10/cache/disk/disk.go#L326C19-L326C19

**Comment by csh2022** [comment]
![image](https://github.com/buchgr/bazel-remote/assets/24428215/bd03e7b2-1f63-4c66-9c19-1b43e1bd4664)

**Comment by mostynb** [comment]
Hi, I think this code is correct- `rc` is passed to `c.proxy.Put(...)` as an `io.ReadCloser`, and the backend proxy's `Put` function is expected to close the file.
