### ISSUE TITLE
BAZEL_REMOTE_MAX_SIZE env variable overwritten when using docker container

### ISSUE THREAD

**Issue by Ryang20718** [buchgr/bazel-remote#689]
```
docker run --rm -p 8080:8080 --env "BAZEL_REMOTE_MAX_SIZE=50" buchgr/bazel-remote-cache:v2.4.1
```

```
> curl localhost:8080/status
{
 "CurrSize": 0,
 "UncompressedSize": 0,
 "ReservedSize": 0,
 "MaxSize": 5368709120,
 "NumFiles": 0,
 "ServerTime": 1692208091,
 "GitCommit": "c5bf6e13938aa89923c637b5a4f01c2203a3c9f8",
 "NumGoroutines": 9
}
```

**Comment by Ryang20718** [comment]
it seems like --max_size is getting appended to the docker run arg

**Comment by mostynb** [comment]
I think this is a result of https://github.com/buchgr/bazel-remote/pull/660 - we provide a default value to the docker image with the `--max_size` command line, and the command line arguments override environment variables.

If you provide a `--max_size` argument on the docker command line, things should work for you. But it might be better if we could provide a default to the docker image via environment variable instead.

**Comment by Ryang20718** [comment]
>If you provide a --max_size argument on the docker command line, things should work for you

Yeah, that's what we ended up doing. 

>But it might be better if we could provide a default to the docker image via environment variable instead.

yeah, we were hoping to have this behaviour as it was before

**Comment by mostynb** [comment]
Oh, wait... #660 landed on the master branch after v2.4.1, I think it actually fixes this issue. If you run the `latest` docker image tag instead of `v2.4.1` it behaves as expected. Could you check if that works for you too?

**Comment by Ryang20718** [comment]
@mostynb works for us!

Wondering when this will a release version?

**Comment by mostynb** [comment]
I made a v2.4.2 release just now, which should include the fix you want.
