### ISSUE TITLE
Support read-only proxy

### ISSUE THREAD

**Issue by uri-canva** [buchgr/bazel-remote#69]
Related to https://github.com/buchgr/bazel-remote/issues/59, I have a setup where developer machines have a local cache they write to, as discussed in https://github.com/bazelbuild/bazel/issues/5139, however to proxy to the shared cache that CI writes to one must also enable writing to it, as there is no configuration knob for that. I could disable writing to the cache on the client side, but then we wouldn't be using the cache running locally as a directory cache.

**Comment by shmish111** [comment]
This also makes it safer to provide a publicly available cache, it provides the benefits of caching anything that builds on CI without the risk of malicious users polluting or PUT DOSing the cache.

**Comment by uri-canva** [comment]
Duplicate of #59.
