### ISSUE TITLE
Add a "Contribute to Bazel-Remote" section in README

### ISSUE THREAD

**Issue by bayareabear** [buchgr/bazel-remote#70]
Include a brief introduction of how to set up the development environment, what's the recommended IDE, how to run test inside IDE, etc..
I tried to set up running test inside Intellij but did not figure out. I just ended up running test in command line with bazel

**Comment by buchgr** [comment]
I also mostly run bazel in the command line and use visual studio code with the go plugin for developing. nothing fancy :-)

**Comment by mostynb** [comment]
Since we don't have a recommended IDE, I'm going to mark this as closed. However, we can add such information later if someone figures out how to do it.
