### ISSUE TITLE
Repeatedly getting no space left on device

### ISSUE THREAD

**Issue by bluelight773** [buchgr/bazel-remote#712]
I have a disk that's slightly larger than `max_size` of the cache, and as I understand, the remote cache evicts based on LRU when full, so why am I constantly getting `no space left on device`:
```
WARNING: Writing to Remote Cache:
500 Internal Server Error
write <CAS_PATH>: no space left on device
```

**Comment by mostynb** [comment]
Hi, the disk usage estimation is only approximate, because finding the exact usage is slow. Have you tried reducing the limit a bit?

**Comment by bluelight773** [comment]
I haven't tried.

Say `max_size` is x GB, how much space should the disk have to avoid/minimize this error? I'm currently using x + 1 GB.

**Comment by ulrfa** [comment]
I suggest setting max_size to 80-85% of the available storage, also in order to reduce file system fragmentation.

**Comment by bluelight773** [comment]
Thanks, will give that try. I'll close the issue and re-open if the issue persists despite the change.

One question though: What happens if I suddenly decrease the `max_size`? Will bazel-remote automatically start evicting to get within the new limit?
