### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by neumann-nico** [buchgr/bazel-remote#722]
When I tried to start bazel-remote with the `:latest` Docker tag I get the following error on startup:

```bash
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/bazel-remote-base.binary": stat /app/bazel-remote-base.binary: no such file or directory: unknown.
```

I get the error on multiple machines and tried to delete the image and pull it again.

Until yesterday the `:latest` image tag worked fine. The tag `:latest-2.4` works fine too, so only todays build seems broken.

This might be an issue with the latest changes #720 and maybe previous OCI changes?

**Comment by mostynb** [comment]
Thanks for reporting this- I pushed a slightly older build so it should be working again now.

It is related to the OCI changes somehow, I will figure out the problem and add some tests before pushing to dockerhub again.

**Comment by neumann-nico** [comment]
Thanks for your hard work!

**Comment by mostynb** [comment]
This should be fixed properly now. I pushed to latest and it still seems to work.

**Comment by neumann-nico** [comment]
It works fine on x64, but on arm64 I get:

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bazel-remote": stat /bazel-remote: no such file or directory: unknown.`

**Comment by mostynb** [comment]
The arm build should be fixed now also (added a test to cover this too).

**Comment by neumann-nico** [comment]
Thanks now arm64 works too 🚀
