### ISSUE TITLE
Build failed when executing bazelisk run :bazel-remote-image

### ISSUE THREAD

**Issue by imooccodejesse** [buchgr/bazel-remote#745]
OS: Ubuntu `18.04.6`
bazel ver: `7.1.2`
bazel-remote ver: `2.3.9`
executed cmd: `bazelisk run :bazel-remote-image`

Error message:
```
ERROR: /home/fooUser/.cache/bazel/_bazel_jesseha/e3f7713d09e01c16632e8bfb216ed4bf/external/io_bazel_rules_go/BUILD.    bazel:71:16: in (an implicit dependency) attribute of go_context_data rule @@io_bazel_rules_go//:go_context_data: in whitelist_function_transition attribute of go_context_data rule @@io_bazel_rules_go//:go_context_data: package group '@@bazel_tools//tools/whitelists/function_transition_whitelist: function_transition_whitelist' is misplaced here (they are only all owed in the visibility attribute)
```

![image](https://github.com/buchgr/bazel-remote/assets/35806700/06f6c765-c6f8-4c9b-96ce-0df7617609b8)

**Comment by mostynb** [comment]
Hi, I think you will need an older version of bazel to build that version of bazel-remote. If you set `USE_BAZEL_VERSION=6.5.0` then bazelisk will use that version, the build should work.

However, bazel doesn't seem to know how to run the image targets anymore. If you want to build and run locally, I suggest using the //:bazel-remote or //:bazel-remote-linux-amd64 targets.

**Comment by imooccodejesse** [comment]
Hi. Thanks for looking into the issue. I solve the issue by pulling the docker image from the public docker image repo instead of building the image.
