### ISSUE TITLE
Build release binaries on ubuntu-20.04

### ISSUE THREAD

**Issue by criemen** [buchgr/bazel-remote#763]
HI,

would it be possible to switch release binary building to Ubuntu 20.04? As you're building a cgo binary, it depends on glibc, which in turn depends on the precise glibc version of the toolchain used (usually: the build host).
I'd like to deploy `bazel-remote` into a Ubuntu 20.04 environment, but it doesn't start, as the glibc there is too old.

I wanted to prepare a PR to your release workflow to that effect, but as that's already failing on arm64, I'm not sure how useful that would be.

**Comment by mostynb** [comment]
Sorry about this. I need to find some time to fix the release workflow. In the meantime, I replaced https://github.com/buchgr/bazel-remote/releases/download/v2.4.4/bazel-remote-2.4.4-linux-x86_64 with a version build on ubuntu 20.04.

I will close this issue now, and fix the release process before the next release.

**Comment by criemen** [comment]
Thank you for the quick help ❤

**Comment by adamiBs** [comment]
Hi @mostynb 
This still seems to reproduce on Ubuntu 20.04

Any change that you know what was the latest version that was compiled on Ubuntu 20.04?

**Comment by mostynb** [comment]
@adamiBs: oops, I have updated the v2.5.2 and v2.6.0 linux amd64 binaries with versions built to run on ubuntu 20.04 and later.
