### ISSUE TITLE
Does bazel-remote work with --experimental_enable_bzlmod

### ISSUE THREAD

**Issue by printharsh** [buchgr/bazel-remote#766]
We have bzlmod enabled, and are trying to remote cache.

For testing I'm running the bazel remote cache server locally and trying to get it to hit by bazel cleaning and building.
bazel build --remote_cache=http://localhost:8080 --remote_upload_local_results=true //target

From the docker container that's running for bazel-remote, it never gets called and the stats show nothing either.

**Comment by mostynb** [comment]
That looks like it should work. You can test that the docker container is reachable by doing something like `wget -q -O - http://localhost:8080/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (that will try to fetch the empty blob and print it to the screen). If that works, you should see a corresponding log line from bazel-remote.

Does bazel log anything related to the cache not being reachable?

**Comment by mostynb** [comment]
Closing due to lack of feedback.

bazel-remote is itself built using bzlmod now, and our CI jobs confirm that this works.
