### ISSUE TITLE
Why is the cache directory 744?

### ISSUE THREAD

**Issue by ob** [buchgr/bazel-remote#78]
Is there any reason the cache directory defaults to 0744 instead of the more common 0755 or even respecting `umask`?

I'm talking about [this code](https://github.com/buchgr/bazel-remote/blob/master/cache/disk/disk.go#L291).

**Comment by mostynb** [comment]
I'm not sure why 0744 was chosen, but it has one possibly useful quality: it prevents other users from listing the directory, which can be a very slow operation if the cache is large.

**Comment by ob** [comment]
True, but it also makes managing the cache harder on servers where you might not have root and bazel-remote is run under some other user.
