### ISSUE TITLE
How to clear the cache manually

### ISSUE THREAD

**Issue by BrandonThomasJonesARM** [buchgr/bazel-remote#788]
In our use case, there are occasions where we have very large objects and the cache is close to full.

I think the behavior I am seeing in this case is the object failing to get put into the cache successfully. Is there a way without turning off the server to allow for a bigger cleanup request?

**Comment by mostynb** [comment]
Bazel-remote manages the disk usage itself, as long as clients aren't requesting a blob, it will eventually reach the top of the LRU index and be removed. You should not need to manually clear the cache directory, if you do then that would be considered a bug (but if you really want to do this, the only way is to stop bazel-remote, and restart it once you have finished removing cache files).

Is there a specific problem you're seeing?

**Comment by apipe** [comment]
We are seeing this issue as well. Log shows lots of error messages like

`GRPC BYTESTREAM WRITE FAILED: uploads/ac41810c-982d-4f02-aa19-3153f94eb3f2/compressed-blobs/zstd/d16c7416a6d6d6da53c93ee45726403c1c7d291ba942e24aac19967d09e47a73/148 Cache Put failed: Failed to write compressed CAS blob to disk: write /data/cas.v2/d1/d16c7416a6d6d6da53c93ee45726403c1c7d291ba942e24aac19967d09e47a73-148-481930764: no space left on device`

**Comment by mostynb** [comment]
@apipe: it looks like you have run out of disk space: `no space left on device`. You should either try to free up some disk space outside of bazel-remote's data directory, or restart bazel-remote with a lower `--max_size` value.

**Comment by mostynb** [comment]
Closing this issue, I think I answered everyone here.

In summary: don't try to delete cache items from disk while bazel-remote is running, and ensure that you have enough disk space allocated and a suitable `--max_size` / `BAZEL_REMOTE_MAX_SIZE` setting.
