### ISSUE TITLE
Issue v1.3.4 was releaseed after v2.4.4 why

### ISSUE THREAD

**Issue by clintonsteiner** [buchgr/bazel-remote#790]
Which is the most recent version? Why did we go backwards in versioning?

**Comment by mostynb** [comment]
It depends what you mean by "most recent version".

v1.3.4 was a maintenance release with a security fix for people still running 1.3.x, that happened to be made after the v2.4.4 release (which is the most current release).

**Comment by clintonsteiner** [comment]
Thank you! I wondered about that but wanted to confirm since the older versions were still around with no patches

**Comment by mostynb** [comment]
It's a bit of an annoying quirk of the github web ui :(
