### ISSUE TITLE
"Insufficient Storage" despite high maximum blob size

### ISSUE THREAD

**Issue by njlr** [buchgr/bazel-remote#798]
I am using Bazel Remote with an S3 backend. 

I am seeing this error on large artifacts:

```
WARNING: Remote Cache: 507 Insufficient Storage
The item (5484789760) + reserved space is larger than the cache's maximum size (5368709120).
com.google.***tools.build.lib.remote.common.BulkTransferException: 507 Insufficient Storage
The item (5484789760) + reserved space is larger than the cache's maximum size (5368709120).
```

This is surprising because I have configured `BAZEL_REMOTE_MAX_BLOB_SIZE` to `10737418240`.

Any ideas why a size limit is being hit?

**Comment by mostynb** [comment]
Hi, bazel-remote first stores incoming blobs in its filesystem cache, and then copies them to the optional proxy backends. The filesystem cache needs to be large enough to hold all the incoming blobs at once, or you get this error message.

It looks like you are using a 5GiB filesystem cache (the default value for the docker image), and a client tried to upload a blob larger than 5GiB.

**Comment by njlr** [comment]
> Hi, bazel-remote first stores incoming blobs in its filesystem cache, and then copies them to the optional proxy backends. The filesystem cache needs to be large enough to hold all the incoming blobs at once, or you get this error message.
> 
> It looks like you are using a 5GiB filesystem cache (the default value for the docker image), and a client tried to upload a blob larger than 5GiB.

Thanks - this makes sense. 

To increase this limit (say to 10GiB), should I set `BAZEL_REMOTE_MAX_SIZE`?

**Comment by mostynb** [comment]
> To increase this limit (say to 10GiB), which variable should I set? `BAZEL_REMOTE_MAX_SIZE`?

Yes, exactly.
