### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [buchgr/bazel-remote#82]
This repository cannot build with Bazel incompatible flags.
At least `--incompatible_no_transitive_loads` is failing, probably more.

[`bazelisk --migrate`](https://github.com/philwo/bazelisk#other-features) can be useful to find the issues.

Could you fix the issues?
Thanks

**Comment by laurentlb** [comment]
Based on our last CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/31#ee7d9f30-83a1-4f3f-8193-f699f70c640a), migration is needed for the following flags:

* `--incompatible_depset_is_not_iterable`
* `--incompatible_disable_deprecated_attr_params`
* `--incompatible_new_actions_api`
* `--incompatible_no_support_tools_in_action_inputs`
* `--incompatible_no_transitive_loads`

Please take a look

**Comment by laurentlb** [comment]
ping @buchgr

**Comment by meteorcloudy** [comment]
The project is disabled in [Bazel's downstream test](https://buildkite.com/bazel/bazel-at-head-plus-downstream) due to this issue, please help fixing.

**Comment by buchgr** [comment]
this has been fixed.
