### ISSUE TITLE
Protect external dependencies from deletion

### ISSUE THREAD

**Issue by Globegitter** [buchgr/bazel-remote#9]
Not sure if that is possible, but it would be nice to somehow protect external dependencies from being automatically deleted. The idea behind this is to be able to still enforce a maximum size for project targets but be guaranteed to have your external dependencies at all times and therefore have some protection against the case of third party dependencies having been removed or internet downtime (given the server being in the local network).

Let me know what you think of this idea.

**Comment by buchgr** [comment]
Hi Markus, 

what exactly do you mean by external dependencies? Do you mean dependencies specified via `remote_repository`? Also, what do you mean by dependencies having been removed? Removed from where?

I think I need a bit more context of the intended use case here :-). Where do you run the cache?

Thanks!

**Comment by Globegitter** [comment]
Hi Jakob,

I basically mean dependencies defined in the `WORKSPACE` file, so `http_archive`, `go_repository` etc.  Or is that not something that is not being cached currently?

The idea is along the lines of having a mirror of external dependencies (other bazel rules, external go libraries, etc). I.e. download the dependencies once and then company-internal they are just being shared throughout the cache. At the same time I still want to be able to specify a `max_size` so there are still bounds on parts of the cache that we can afford to loose. Hope that makes more sense, but let me know if anything is still unclear.

**Comment by buchgr** [comment]
Ohh I see what you mean. That's currently not being cached and that's also not something the remote cache could cache, as Bazel only ever sends build outputs to it and not inputs i.e. dependencies.

Bazel does cache these dependencies locally, however. So as long as you don't do a `bazel clean` these should be cached. More generally I think what you are looking for is a caching proxy, that mirrors your dependencies. Servers like nginx can do that.

I ll close this for now.
