### ISSUE TITLE
Add Prometheus support for metrics

### ISSUE THREAD

**Issue by GabrielGhe** [buchgr/bazel-remote#95]
One of the most important features for any remote cache (IMO) is metrics. We want to know how healthy the cache is and be notified if something changes.

Adding support for Prometheus would give us that functionality.

**Comment by ob** [comment]
I think this could be split in two pieces. One is just tracking all the metrics, regardless of how they are published. We could add an endpoint (e.g. `/metrics`) that just prints out JSON or HTML. 

Once we have the information there should be a way to plug in different metric collectors (e.g. Prometheus). We added metrics to our internal fork, but they publish via Kafka.

@bdittmer, how hard would it be to put together a PR _collecting_ the metrics to an end-point and ignoring the publishing for now?

**Comment by davidlee1435** [comment]
Hey folks, any update on this? We're exploring using this repo and would like to send metrics to Datadog.

**Comment by mostynb** [comment]
I don't think anyone has started on this yet. Which metrics would you want to use?

**Comment by davidlee1435** [comment]
It looks like there are some metrics that we could leverage with `/status`, like currSize, maxSize, and numFiles (https://github.com/buchgr/bazel-remote/issues/48). I think that this is sufficient for us at the moment.

**Comment by mostynb** [comment]
Here's a PR that adds some basic prometheus metrics + cache hit/miss counts: #160.

**Comment by mostynb** [comment]
Landed #160 with some cache hit/miss counters, but without the data from /status for now.

Please open a new issue if these metrics aren't useful or if there are other metrics you think might be worth adding.

**Comment by davidlee1435** [comment]
Thanks @mostynb! Will the image on Docker Hub contain these changes?

**Comment by mostynb** [comment]
I'm not sure, we'll have to wait for @buchgr to do it.

But it's fairly easy to build your own image and install it in your local docker registry:
`bazel run :bazel-remote-image`

**Comment by buchgr** [comment]
@davidlee1435 I just pushed to DockerHub
